// Generated by gen_levels.py — SQL chapters. One new idea per quest.
(function () {
  window.SQL_LEVELS = [
 {
  "id": "sq1",
  "tables": [
   "mobs"
  ],
  "text": {
   "en": {
    "title": "Open the Mobdex",
    "story": "You found an ancient Mobdex — a database with info on every mob. It only answers questions written in <b>SQL</b>, the language real data analysts use every day."
   },
   "es": {
    "title": "Abre el Mobdex",
    "story": "Has encontrado un Mobdex antiguo — una base de datos con información de cada criatura. Solo responde a preguntas escritas en <b>SQL</b>, el lenguaje que usan los analistas de datos cada día."
   },
   "de": {
    "title": "Öffne den Mobdex",
    "story": "Du hast einen uralten Mobdex gefunden — eine Datenbank mit Infos über jeden Mob. Er beantwortet nur Fragen in <b>SQL</b>, der Sprache, die echte Datenanalysten jeden Tag benutzen."
   }
  },
  "quests": [
   {
    "answer": "DESCRIBE mobs",
    "example": "DESCRIBE mobs",
    "text": {
     "en": {
      "idea": "DESCRIBE",
      "lesson": "Before you use a table, look at what's in it. <code>DESCRIBE mobs</code> lists every <b>column</b> and its <b>type</b>: <code>TEXT</code> means words, <code>INTEGER</code> means whole numbers. Remember the types — they matter later! (Some databases use a different command for this, but the habit is the same.)",
      "task": "Meet your first table: see which columns <code>mobs</code> has. The code is already there — just press ▶ Run!",
      "hint": "Just press Run 🙂"
     },
     "es": {
      "idea": "DESCRIBE",
      "lesson": "Antes de usar una tabla, mira qué contiene. <code>DESCRIBE mobs</code> muestra cada <b>columna</b> y su <b>tipo</b>: <code>TEXT</code> son palabras, <code>INTEGER</code> son números enteros. ¡Recuerda los tipos, importan más adelante! (Algunas bases de datos usan otro comando para esto, pero la costumbre es la misma.)",
      "task": "Conoce tu primera tabla: mira qué columnas tiene <code>mobs</code>. El código ya está escrito — ¡solo pulsa ▶ Ejecutar!",
      "hint": "Solo pulsa Ejecutar 🙂"
     },
     "de": {
      "idea": "DESCRIBE",
      "lesson": "Bevor du eine Tabelle benutzt, schau, was drin ist. <code>DESCRIBE mobs</code> zeigt jede <b>Spalte</b> und ihren <b>Typ</b>: <code>TEXT</code> sind Wörter, <code>INTEGER</code> sind ganze Zahlen. Merk dir die Typen — die sind später wichtig! (Manche Datenbanken nehmen dafür einen anderen Befehl, aber die Gewohnheit ist dieselbe.)",
      "task": "Lern deine erste Tabelle kennen: Schau, welche Spalten <code>mobs</code> hat. Der Code steht schon da — drück einfach ▶ Start!",
      "hint": "Drück einfach Start 🙂"
     }
    },
    "starter": "DESCRIBE mobs",
    "unlock": {
     "mobs": [
      1
     ]
    }
   },
   {
    "answer": "SELECT * FROM mobs",
    "example": "SELECT * FROM mobs",
    "text": {
     "en": {
      "idea": "SELECT * FROM",
      "lesson": "Now look at the actual data. <code>SELECT</code> says what you want to see, <code>FROM</code> says which table. <code>*</code> means \"every column\".",
      "task": "Show <b>everything</b> in the <code>mobs</code> table — this time you type it yourself.",
      "hint": "SELECT * FROM mobs"
     },
     "es": {
      "idea": "SELECT * FROM",
      "lesson": "Ahora mira los datos de verdad. <code>SELECT</code> dice qué quieres ver, <code>FROM</code> de qué tabla. <code>*</code> significa \"todas las columnas\".",
      "task": "Muestra <b>todo</b> lo que hay en la tabla <code>mobs</code> — esta vez lo escribes tú.",
      "hint": "SELECT * FROM mobs"
     },
     "de": {
      "idea": "SELECT * FROM",
      "lesson": "Jetzt schau dir die echten Daten an. <code>SELECT</code> sagt, was du sehen willst, <code>FROM</code> aus welcher Tabelle. <code>*</code> heißt \"alle Spalten\".",
      "task": "Zeig <b>alles</b> aus der Tabelle <code>mobs</code> — diesmal tippst du es selbst.",
      "hint": "SELECT * FROM mobs"
     }
    },
    "unlock": {
     "mobs": [
      2,
      14
     ]
    }
   },
   {
    "answer": "SELECT name, health FROM mobs",
    "example": "SELECT name, type FROM mobs",
    "text": {
     "en": {
      "idea": "Pick columns",
      "lesson": "Instead of <code>*</code>, write the column names you want, separated by <b>commas</b>. The tables on the right show every column name.",
      "task": "Show only the <b>name</b> and <b>health</b> of every mob.",
      "hint": "Replace * with the two column names, with a comma between them."
     },
     "es": {
      "idea": "Elegir columnas",
      "lesson": "En lugar de <code>*</code>, escribe los nombres de las columnas que quieres, separados por <b>comas</b>. Las tablas de la derecha muestran todos los nombres.",
      "task": "Muestra solo el <b>name</b> y la <b>health</b> de cada criatura.",
      "hint": "Cambia el * por los dos nombres de columna, con una coma entre ellos."
     },
     "de": {
      "idea": "Spalten auswählen",
      "lesson": "Statt <code>*</code> schreibst du die Spaltennamen, die du willst, getrennt durch <b>Kommas</b>. Rechts siehst du alle Spaltennamen.",
      "task": "Zeig nur <b>name</b> und <b>health</b> von jedem Mob.",
      "hint": "Ersetze * durch die zwei Spaltennamen, mit einem Komma dazwischen."
     }
    },
    "unlock": {
     "mobs": [
      3,
      15
     ]
    }
   },
   {
    "answer": "SELECT name, health FROM mobs ORDER BY health DESC",
    "example": "SELECT name, damage FROM mobs ORDER BY damage",
    "text": {
     "en": {
      "idea": "ORDER BY",
      "lesson": "<code>ORDER BY column</code> sorts the rows, smallest first. Add <code>DESC</code> to put the biggest first. It goes at the end of the query.",
      "task": "Show <b>name</b> and <b>health</b>, sorted from the <b>most</b> health to the least.",
      "hint": "Add ORDER BY health DESC at the end."
     },
     "es": {
      "idea": "ORDER BY",
      "lesson": "<code>ORDER BY columna</code> ordena las filas, de menor a mayor. Añade <code>DESC</code> para poner primero el mayor. Va al final de la consulta.",
      "task": "Muestra <b>name</b> y <b>health</b>, ordenados de <b>más</b> vida a menos.",
      "hint": "Añade ORDER BY health DESC al final."
     },
     "de": {
      "idea": "ORDER BY",
      "lesson": "<code>ORDER BY spalte</code> sortiert die Zeilen, das Kleinste zuerst. Mit <code>DESC</code> kommt das Größte zuerst. Es steht am Ende der Abfrage.",
      "task": "Zeig <b>name</b> und <b>health</b>, sortiert vom <b>meisten</b> Leben zum wenigsten.",
      "hint": "Schreib ORDER BY health DESC ans Ende."
     }
    },
    "orderCol": 1,
    "unlock": {
     "mobs": [
      4,
      17
     ]
    }
   },
   {
    "answer": "SELECT name, health FROM mobs ORDER BY health DESC LIMIT 3",
    "example": "SELECT name, damage FROM mobs ORDER BY damage DESC LIMIT 5",
    "text": {
     "en": {
      "idea": "LIMIT",
      "lesson": "<code>LIMIT 5</code> keeps only the first 5 rows. Together with ORDER BY it makes a \"top 5\".",
      "task": "Show <b>name</b> and <b>health</b> of the <b>3 toughest</b> mobs.",
      "hint": "Sort by health, biggest first, then add LIMIT 3."
     },
     "es": {
      "idea": "LIMIT",
      "lesson": "<code>LIMIT 5</code> se queda solo con las 5 primeras filas. Junto con ORDER BY te da un \"top 5\".",
      "task": "Muestra <b>name</b> y <b>health</b> de las <b>3 más resistentes</b>.",
      "hint": "Ordena por health de mayor a menor y añade LIMIT 3."
     },
     "de": {
      "idea": "LIMIT",
      "lesson": "<code>LIMIT 5</code> behält nur die ersten 5 Zeilen. Zusammen mit ORDER BY ergibt das eine \"Top 5\".",
      "task": "Zeig <b>name</b> und <b>health</b> der <b>3 zähesten</b> Mobs.",
      "hint": "Sortier nach health, das Größte zuerst, dann LIMIT 3."
     }
    },
    "orderCol": 1,
    "unlock": {
     "mobs": [
      10
     ]
    }
   },
   {
    "answer": "SELECT DISTINCT home FROM mobs",
    "example": "SELECT DISTINCT type FROM mobs",
    "text": {
     "en": {
      "idea": "DISTINCT",
      "lesson": "Many mobs share the same home. <code>SELECT DISTINCT</code> removes duplicate rows, so every value shows up only once.",
      "task": "Which <b>different homes</b> exist? Show each home only <b>once</b>.",
      "hint": "Put DISTINCT right after SELECT."
     },
     "es": {
      "idea": "DISTINCT",
      "lesson": "Muchas criaturas comparten hogar. <code>SELECT DISTINCT</code> quita las filas repetidas, así cada valor aparece una sola vez.",
      "task": "¿Qué <b>hogares distintos</b> hay? Muestra cada hogar <b>una sola vez</b>.",
      "hint": "Pon DISTINCT justo después de SELECT."
     },
     "de": {
      "idea": "DISTINCT",
      "lesson": "Viele Mobs haben dasselbe Zuhause. <code>SELECT DISTINCT</code> entfernt doppelte Zeilen, so kommt jeder Wert nur einmal vor.",
      "task": "Welche <b>verschiedenen Zuhause</b> gibt es? Zeig jedes nur <b>einmal</b>.",
      "hint": "Schreib DISTINCT direkt hinter SELECT."
     }
    },
    "unlock": {
     "mobs": [
      16,
      9
     ]
    }
   },
   {
    "answer": "SELECT name, damage * 3 AS three_hits FROM mobs",
    "example": "SELECT name, health * 2 AS double_health FROM mobs",
    "text": {
     "en": {
      "idea": "Maths and AS",
      "lesson": "You can calculate inside SELECT with <code>+ - * /</code>. <code>AS</code> gives the new column a name — otherwise it gets an ugly name like <code>damage * 3</code>.",
      "task": "A mob hits you <b>3 times</b>. Show each mob's <b>name</b> and its total damage, in a column called <code>three_hits</code>.",
      "hint": "Multiply damage * 3, then name it with AS three_hits."
     },
     "es": {
      "idea": "Cálculos y AS",
      "lesson": "Puedes calcular dentro del SELECT con <code>+ - * /</code>. <code>AS</code> le pone nombre a la nueva columna — si no, se llama algo feo como <code>damage * 3</code>.",
      "task": "Una criatura te golpea <b>3 veces</b>. Muestra el <b>name</b> de cada una y su daño total, en una columna llamada <code>three_hits</code>.",
      "hint": "Multiplica damage * 3 y ponle nombre con AS three_hits."
     },
     "de": {
      "idea": "Rechnen und AS",
      "lesson": "Im SELECT kannst du mit <code>+ - * /</code> rechnen. <code>AS</code> gibt der neuen Spalte einen Namen — sonst heißt sie hässlich, zum Beispiel <code>damage * 3</code>.",
      "task": "Ein Mob trifft dich <b>3-mal</b>. Zeig den <b>name</b> jedes Mobs und seinen Gesamtschaden, in einer Spalte namens <code>three_hits</code>.",
      "hint": "Rechne damage * 3 und gib ihm mit AS three_hits einen Namen."
     }
    },
    "requireNames": true,
    "unlock": {
     "mobs": [
      5,
      11
     ]
    }
   }
  ]
 },
 {
  "id": "sq2",
  "tables": [
   "mobs"
  ],
  "text": {
   "en": {
    "title": "Mob Hunter",
    "story": "Night is coming and you need to know <b>exactly</b> which mobs to watch out for. Time to <b>filter</b> the Mobdex."
   },
   "es": {
    "title": "Cazador de criaturas",
    "story": "Se acerca la noche y necesitas saber <b>exactamente</b> de qué criaturas cuidarte. Es hora de <b>filtrar</b> el Mobdex."
   },
   "de": {
    "title": "Mob-Jäger",
    "story": "Die Nacht kommt, und du musst <b>genau</b> wissen, vor welchen Mobs du aufpassen musst. Zeit, den Mobdex zu <b>filtern</b>."
   }
  },
  "quests": [
   {
    "answer": "SELECT * FROM mobs WHERE type = 'hostile'",
    "example": "SELECT name FROM mobs WHERE type = 'passive'",
    "text": {
     "en": {
      "idea": "WHERE",
      "lesson": "<code>WHERE</code> keeps only the rows that match a rule. It comes right after <code>FROM</code>. Remember DESCRIBE? <code>type</code> is <code>TEXT</code> — and text always goes in <b>single quotes</b>: <code>'hostile'</code>.",
      "task": "Show all columns, but only for <b>hostile</b> mobs.",
      "hint": "WHERE type = 'hostile' — don't forget the quotes."
     },
     "es": {
      "idea": "WHERE",
      "lesson": "<code>WHERE</code> se queda solo con las filas que cumplen una regla. Va justo después de <code>FROM</code>. ¿Recuerdas DESCRIBE? <code>type</code> es <code>TEXT</code> — y el texto siempre va entre <b>comillas simples</b>: <code>'hostile'</code>.",
      "task": "Muestra todas las columnas, pero solo de las criaturas <b>hostile</b>.",
      "hint": "WHERE type = 'hostile' — no olvides las comillas."
     },
     "de": {
      "idea": "WHERE",
      "lesson": "<code>WHERE</code> behält nur die Zeilen, die zu einer Regel passen. Es kommt direkt nach <code>FROM</code>. Erinnerst du dich an DESCRIBE? <code>type</code> ist <code>TEXT</code> — und Text kommt immer in <b>einfache Anführungszeichen</b>: <code>'hostile'</code>.",
      "task": "Zeig alle Spalten, aber nur für <b>hostile</b> Mobs.",
      "hint": "WHERE type = 'hostile' — vergiss die Anführungszeichen nicht."
     }
    },
    "unlock": {
     "mobs": [
      6
     ]
    }
   },
   {
    "answer": "SELECT name FROM mobs WHERE health > 20",
    "example": "SELECT name, damage FROM mobs WHERE damage >= 10",
    "text": {
     "en": {
      "idea": "Compare numbers",
      "lesson": "For numbers: <code>&gt;</code> bigger, <code>&lt;</code> smaller, <code>&gt;=</code> bigger or equal, <code>&lt;=</code> smaller or equal, <code>!=</code> not equal. <code>health</code> is an <code>INTEGER</code>, so it needs <b>no</b> quotes.",
      "task": "Show the <b>name</b> of every mob with <b>more than 20</b> health.",
      "hint": "\"More than\" is &gt;."
     },
     "es": {
      "idea": "Comparar números",
      "lesson": "Para números: <code>&gt;</code> mayor, <code>&lt;</code> menor, <code>&gt;=</code> mayor o igual, <code>&lt;=</code> menor o igual, <code>!=</code> distinto. <code>health</code> es <code>INTEGER</code>, así que <b>no</b> lleva comillas.",
      "task": "Muestra el <b>name</b> de cada criatura con <b>más de 20</b> de vida.",
      "hint": "\"Más de\" es &gt;."
     },
     "de": {
      "idea": "Zahlen vergleichen",
      "lesson": "Für Zahlen: <code>&gt;</code> größer, <code>&lt;</code> kleiner, <code>&gt;=</code> größer oder gleich, <code>&lt;=</code> kleiner oder gleich, <code>!=</code> ungleich. <code>health</code> ist ein <code>INTEGER</code>, also braucht es <b>keine</b> Anführungszeichen.",
      "task": "Zeig den <b>name</b> jedes Mobs mit <b>mehr als 20</b> Leben.",
      "hint": "\"Mehr als\" ist &gt;."
     }
    },
    "unlock": {
     "mobs": [
      7
     ]
    }
   },
   {
    "answer": "SELECT name FROM mobs WHERE type = 'hostile' AND home = 'overworld'",
    "example": "SELECT name FROM mobs WHERE type = 'passive' AND health > 10",
    "text": {
     "en": {
      "idea": "AND",
      "lesson": "<code>AND</code> joins two rules: a row stays only if <b>both</b> are true.",
      "task": "Show the <b>name</b> of the <b>hostile</b> mobs that live in the <b>overworld</b>.",
      "hint": "Two rules: type = 'hostile' AND home = 'overworld'"
     },
     "es": {
      "idea": "AND",
      "lesson": "<code>AND</code> une dos reglas: una fila se queda solo si <b>las dos</b> son ciertas.",
      "task": "Muestra el <b>name</b> de las criaturas <b>hostile</b> que viven en el <b>overworld</b>.",
      "hint": "Dos reglas: type = 'hostile' AND home = 'overworld'"
     },
     "de": {
      "idea": "AND",
      "lesson": "<code>AND</code> verbindet zwei Regeln: Eine Zeile bleibt nur, wenn <b>beide</b> stimmen.",
      "task": "Zeig den <b>name</b> der <b>hostile</b> Mobs, die in der <b>overworld</b> leben.",
      "hint": "Zwei Regeln: type = 'hostile' AND home = 'overworld'"
     }
    },
    "unlock": {
     "mobs": [
      8
     ]
    }
   },
   {
    "answer": "SELECT name, home FROM mobs WHERE home = 'nether' OR home = 'end'",
    "example": "SELECT name FROM mobs WHERE damage > 20 OR health > 50",
    "text": {
     "en": {
      "idea": "OR",
      "lesson": "<code>OR</code>: a row stays if <b>at least one</b> of the rules is true.",
      "task": "Show <b>name</b> and <b>home</b> of the mobs from the <b>nether</b> or the <b>end</b>.",
      "hint": "home = 'nether' OR home = 'end'"
     },
     "es": {
      "idea": "OR",
      "lesson": "<code>OR</code>: una fila se queda si <b>al menos una</b> de las reglas es cierta.",
      "task": "Muestra <b>name</b> y <b>home</b> de las criaturas del <b>nether</b> o del <b>end</b>.",
      "hint": "home = 'nether' OR home = 'end'"
     },
     "de": {
      "idea": "OR",
      "lesson": "<code>OR</code>: Eine Zeile bleibt, wenn <b>mindestens eine</b> der Regeln stimmt.",
      "task": "Zeig <b>name</b> und <b>home</b> der Mobs aus dem <b>nether</b> oder dem <b>end</b>.",
      "hint": "home = 'nether' OR home = 'end'"
     }
    },
    "unlock": {
     "mobs": [
      12
     ]
    }
   },
   {
    "answer": "SELECT name, loot FROM mobs WHERE loot IN ('bone', 'string', 'gunpowder')",
    "example": "SELECT name FROM mobs WHERE home IN ('caves', 'end')",
    "text": {
     "en": {
      "idea": "IN",
      "lesson": "<code>IN (…)</code> checks against a whole list — a shortcut for many ORs.",
      "task": "Show <b>name</b> and <b>loot</b> of the mobs that drop <b>bone</b>, <b>string</b> or <b>gunpowder</b>.",
      "hint": "loot IN ('bone', 'string', 'gunpowder')"
     },
     "es": {
      "idea": "IN",
      "lesson": "<code>IN (…)</code> compara con una lista entera — un atajo para muchos OR.",
      "task": "Muestra <b>name</b> y <b>loot</b> de las criaturas que sueltan <b>bone</b>, <b>string</b> o <b>gunpowder</b>.",
      "hint": "loot IN ('bone', 'string', 'gunpowder')"
     },
     "de": {
      "idea": "IN",
      "lesson": "<code>IN (…)</code> prüft gegen eine ganze Liste — eine Abkürzung für viele ORs.",
      "task": "Zeig <b>name</b> und <b>loot</b> der Mobs, die <b>bone</b>, <b>string</b> oder <b>gunpowder</b> fallen lassen.",
      "hint": "loot IN ('bone', 'string', 'gunpowder')"
     }
    },
    "unlock": {
     "mobs": [
      13
     ]
    }
   },
   {
    "answer": "SELECT name, health FROM mobs WHERE health BETWEEN 10 AND 20",
    "example": "SELECT name, damage FROM mobs WHERE damage BETWEEN 5 AND 10",
    "text": {
     "en": {
      "idea": "BETWEEN",
      "lesson": "<code>BETWEEN 5 AND 10</code> keeps values from 5 to 10 — <b>including</b> 5 and 10.",
      "task": "Show <b>name</b> and <b>health</b> of the mobs with health <b>between 10 and 20</b>.",
      "hint": "health BETWEEN 10 AND 20"
     },
     "es": {
      "idea": "BETWEEN",
      "lesson": "<code>BETWEEN 5 AND 10</code> se queda con los valores de 5 a 10 — <b>incluidos</b> el 5 y el 10.",
      "task": "Muestra <b>name</b> y <b>health</b> de las criaturas con vida <b>entre 10 y 20</b>.",
      "hint": "health BETWEEN 10 AND 20"
     },
     "de": {
      "idea": "BETWEEN",
      "lesson": "<code>BETWEEN 5 AND 10</code> behält Werte von 5 bis 10 — <b>mit</b> 5 und 10.",
      "task": "Zeig <b>name</b> und <b>health</b> der Mobs mit Leben <b>zwischen 10 und 20</b>.",
      "hint": "health BETWEEN 10 AND 20"
     }
    },
    "unlock": {
     "mobs": [
      18
     ]
    }
   },
   {
    "answer": "SELECT name FROM mobs WHERE name LIKE '%skeleton%'",
    "example": "SELECT name FROM mobs WHERE name LIKE 'S%'",
    "text": {
     "en": {
      "idea": "LIKE",
      "lesson": "<code>LIKE</code> searches text with a pattern. <code>%</code> means \"any letters (or none)\": <code>'S%'</code> finds names starting with S, <code>'%ie%'</code> finds \"ie\" anywhere.",
      "task": "Show the <b>name</b> of every mob with <b>skeleton</b> anywhere in its name.",
      "hint": "Put % on both sides: '%skeleton%'"
     },
     "es": {
      "idea": "LIKE",
      "lesson": "<code>LIKE</code> busca texto con un patrón. <code>%</code> significa \"cualquier letra (o ninguna)\": <code>'S%'</code> encuentra nombres que empiezan por S, <code>'%ie%'</code> encuentra \"ie\" en cualquier parte.",
      "task": "Muestra el <b>name</b> de cada criatura con <b>skeleton</b> en cualquier parte del nombre.",
      "hint": "Pon % a los dos lados: '%skeleton%'"
     },
     "de": {
      "idea": "LIKE",
      "lesson": "<code>LIKE</code> sucht Text mit einem Muster. <code>%</code> heißt \"beliebige Buchstaben (oder keine)\": <code>'S%'</code> findet Namen mit S am Anfang, <code>'%ie%'</code> findet \"ie\" irgendwo.",
      "task": "Zeig den <b>name</b> jedes Mobs, der irgendwo <b>skeleton</b> im Namen hat.",
      "hint": "Setz % auf beide Seiten: '%skeleton%'"
     }
    },
    "unlock": {
     "mobs": [
      19
     ]
    }
   },
   {
    "answer": "SELECT name FROM mobs WHERE loot IS NULL",
    "example": "SELECT name, loot FROM mobs WHERE loot IS NOT NULL",
    "text": {
     "en": {
      "idea": "IS NULL",
      "lesson": "<code>NULL</code> means \"empty — no value at all\". Some mobs drop nothing, so their loot is NULL. <code>= NULL</code> never works; write <code>IS NULL</code> (or <code>IS NOT NULL</code>).",
      "task": "Show the <b>name</b> of the mobs that drop <b>no loot</b>.",
      "hint": "loot IS NULL"
     },
     "es": {
      "idea": "IS NULL",
      "lesson": "<code>NULL</code> significa \"vacío — ningún valor\". Algunas criaturas no sueltan nada, así que su loot es NULL. <code>= NULL</code> nunca funciona; escribe <code>IS NULL</code> (o <code>IS NOT NULL</code>).",
      "task": "Muestra el <b>name</b> de las criaturas que <b>no sueltan nada</b>.",
      "hint": "loot IS NULL"
     },
     "de": {
      "idea": "IS NULL",
      "lesson": "<code>NULL</code> heißt \"leer — gar kein Wert\". Manche Mobs lassen nichts fallen, ihr loot ist NULL. <code>= NULL</code> klappt nie; schreib <code>IS NULL</code> (oder <code>IS NOT NULL</code>).",
      "task": "Zeig den <b>name</b> der Mobs, die <b>keine Beute</b> fallen lassen.",
      "hint": "loot IS NULL"
     }
    },
    "unlock": {
     "mobs": [
      20
     ]
    }
   }
  ]
 },
 {
  "id": "sq3",
  "tables": [
   "hunts"
  ],
  "text": {
   "en": {
    "title": "The Hunt Log",
    "story": "The village keeps a <b>log of every hunt</b>: the table <code>hunts</code>. One row = one hunt: the day, who (<code>player_id</code>), which mob (<code>mob_id</code>), where, how much loot and XP. Time to <b>add things up</b>."
   },
   "es": {
    "title": "El registro de cacerías",
    "story": "La aldea guarda un <b>registro de cada cacería</b>: la tabla <code>hunts</code>. Una fila = una cacería: el día, quién (<code>player_id</code>), qué criatura (<code>mob_id</code>), dónde, cuánto botín y XP. Es hora de <b>sumar</b>."
   },
   "de": {
    "title": "Das Jagdbuch",
    "story": "Das Dorf führt ein <b>Buch über jede Jagd</b>: die Tabelle <code>hunts</code>. Eine Zeile = eine Jagd: der Tag, wer (<code>player_id</code>), welcher Mob (<code>mob_id</code>), wo, wie viel Beute und XP. Zeit <b>zusammenzurechnen</b>."
   }
  },
  "quests": [
   {
    "answer": "DESCRIBE hunts",
    "example": "DESCRIBE hunts",
    "text": {
     "en": {
      "idea": "Describe a new table",
      "lesson": "New table, same habit: <b>describe it first</b>. Look at <code>player_id</code> and <code>mob_id</code> — they are numbers that point to rows in other tables (player 3, mob 6…). You'll connect them in chapter 6.",
      "task": "Before counting anything, <b>describe</b> the <code>hunts</code> table.",
      "hint": "DESCRIBE hunts"
     },
     "es": {
      "idea": "Describe una tabla nueva",
      "lesson": "Tabla nueva, misma costumbre: <b>descríbela primero</b>. Fíjate en <code>player_id</code> y <code>mob_id</code> — son números que apuntan a filas de otras tablas (jugador 3, criatura 6…). Las conectarás en el capítulo 6.",
      "task": "Antes de contar nada, <b>describe</b> la tabla <code>hunts</code>.",
      "hint": "DESCRIBE hunts"
     },
     "de": {
      "idea": "Eine neue Tabelle beschreiben",
      "lesson": "Neue Tabelle, gleiche Gewohnheit: <b>zuerst beschreiben</b>. Schau dir <code>player_id</code> und <code>mob_id</code> an — das sind Zahlen, die auf Zeilen in anderen Tabellen zeigen (Spieler 3, Mob 6…). Die verbindest du in Kapitel 6.",
      "task": "Bevor du etwas zählst: <b>Beschreib</b> die Tabelle <code>hunts</code>.",
      "hint": "DESCRIBE hunts"
     }
    }
   },
   {
    "answer": "SELECT * FROM hunts WHERE day = 1",
    "example": "SELECT * FROM hunts WHERE biome = 'nether'",
    "text": {
     "en": {
      "idea": "A log table",
      "lesson": "Real companies store what happens as a <b>log</b>: one row per event. <code>player_id</code> and <code>mob_id</code> are numbers that point to rows in other tables — you'll connect them later.",
      "task": "Show all hunts from <b>day 1</b>.",
      "hint": "WHERE day = 1"
     },
     "es": {
      "idea": "Una tabla de registro",
      "lesson": "Las empresas guardan lo que pasa como un <b>registro</b>: una fila por cada suceso. <code>player_id</code> y <code>mob_id</code> son números que apuntan a filas de otras tablas — más tarde las conectarás.",
      "task": "Muestra todas las cacerías del <b>día 1</b>.",
      "hint": "WHERE day = 1"
     },
     "de": {
      "idea": "Eine Logtabelle",
      "lesson": "Echte Firmen speichern, was passiert, als <b>Log</b>: eine Zeile pro Ereignis. <code>player_id</code> und <code>mob_id</code> sind Zahlen, die auf Zeilen in anderen Tabellen zeigen — die verbindest du später.",
      "task": "Zeig alle Jagden von <b>Tag 1</b>.",
      "hint": "WHERE day = 1"
     }
    },
    "unlock": {
     "items": [
      1
     ]
    }
   },
   {
    "answer": "SELECT COUNT(*) FROM hunts",
    "example": "SELECT COUNT(*) FROM mobs",
    "text": {
     "en": {
      "idea": "COUNT(*)",
      "lesson": "<code>COUNT(*)</code> counts the rows instead of showing them. You get one number.",
      "task": "<b>How many hunts</b> are in the log?",
      "hint": "SELECT COUNT(*) FROM …"
     },
     "es": {
      "idea": "COUNT(*)",
      "lesson": "<code>COUNT(*)</code> cuenta las filas en vez de mostrarlas. Obtienes un solo número.",
      "task": "¿<b>Cuántas cacerías</b> hay en el registro?",
      "hint": "SELECT COUNT(*) FROM …"
     },
     "de": {
      "idea": "COUNT(*)",
      "lesson": "<code>COUNT(*)</code> zählt die Zeilen, statt sie zu zeigen. Du bekommst eine einzige Zahl.",
      "task": "<b>Wie viele Jagden</b> stehen im Buch?",
      "hint": "SELECT COUNT(*) FROM …"
     }
    },
    "unlock": {
     "items": [
      2
     ]
    }
   },
   {
    "answer": "SELECT SUM(xp) FROM hunts",
    "example": "SELECT SUM(loot_count) FROM hunts",
    "text": {
     "en": {
      "idea": "SUM",
      "lesson": "<code>SUM(column)</code> adds up all the numbers in a column.",
      "task": "How much <b>XP</b> did everybody earn <b>in total</b>?",
      "hint": "SUM(xp)"
     },
     "es": {
      "idea": "SUM",
      "lesson": "<code>SUM(columna)</code> suma todos los números de una columna.",
      "task": "¿Cuánta <b>XP</b> ganaron todos <b>en total</b>?",
      "hint": "SUM(xp)"
     },
     "de": {
      "idea": "SUM",
      "lesson": "<code>SUM(spalte)</code> zählt alle Zahlen einer Spalte zusammen.",
      "task": "Wie viel <b>XP</b> haben alle <b>zusammen</b> verdient?",
      "hint": "SUM(xp)"
     }
    },
    "unlock": {
     "items": [
      3
     ]
    }
   },
   {
    "answer": "SELECT ROUND(AVG(xp), 1) FROM hunts",
    "example": "SELECT ROUND(AVG(health), 1) FROM mobs",
    "text": {
     "en": {
      "idea": "AVG and ROUND",
      "lesson": "<code>AVG(column)</code> is the average. Averages often have long decimals, so <code>ROUND(x, 1)</code> rounds to 1 decimal place.",
      "task": "What is the <b>average XP</b> per hunt, <b>rounded to 1 decimal</b>?",
      "hint": "Put AVG(xp) inside ROUND( … , 1)."
     },
     "es": {
      "idea": "AVG y ROUND",
      "lesson": "<code>AVG(columna)</code> es la media. Las medias suelen tener muchos decimales, así que <code>ROUND(x, 1)</code> redondea a 1 decimal.",
      "task": "¿Cuál es la <b>XP media</b> por cacería, <b>redondeada a 1 decimal</b>?",
      "hint": "Mete AVG(xp) dentro de ROUND( … , 1)."
     },
     "de": {
      "idea": "AVG und ROUND",
      "lesson": "<code>AVG(spalte)</code> ist der Durchschnitt. Der hat oft viele Nachkommastellen, deshalb rundet <code>ROUND(x, 1)</code> auf 1 Stelle.",
      "task": "Wie viel <b>XP</b> bringt eine Jagd <b>im Durchschnitt</b>, <b>auf 1 Stelle gerundet</b>?",
      "hint": "Pack AVG(xp) in ROUND( … , 1)."
     }
    },
    "unlock": {
     "items": [
      4
     ]
    }
   },
   {
    "answer": "SELECT MAX(xp), MIN(xp) FROM hunts",
    "example": "SELECT MIN(health), MAX(health) FROM mobs",
    "text": {
     "en": {
      "idea": "MIN and MAX",
      "lesson": "<code>MIN</code> finds the smallest value, <code>MAX</code> the biggest. You can put several of them in one SELECT.",
      "task": "Show the <b>biggest</b> and the <b>smallest</b> XP from a single hunt.",
      "hint": "SELECT MAX(xp), MIN(xp) …"
     },
     "es": {
      "idea": "MIN y MAX",
      "lesson": "<code>MIN</code> encuentra el valor más pequeño, <code>MAX</code> el más grande. Puedes poner varios en un mismo SELECT.",
      "task": "Muestra la XP <b>más grande</b> y la <b>más pequeña</b> de una sola cacería.",
      "hint": "SELECT MAX(xp), MIN(xp) …"
     },
     "de": {
      "idea": "MIN und MAX",
      "lesson": "<code>MIN</code> findet den kleinsten Wert, <code>MAX</code> den größten. Du kannst mehrere in ein SELECT schreiben.",
      "task": "Zeig die <b>größte</b> und die <b>kleinste</b> XP einer einzelnen Jagd.",
      "hint": "SELECT MAX(xp), MIN(xp) …"
     }
    },
    "unlock": {
     "items": [
      5
     ]
    }
   },
   {
    "answer": "SELECT COUNT(DISTINCT player_id) FROM hunts",
    "example": "SELECT COUNT(DISTINCT home) FROM mobs",
    "text": {
     "en": {
      "idea": "COUNT(DISTINCT)",
      "lesson": "<code>COUNT(DISTINCT column)</code> counts how many <b>different</b> values there are.",
      "task": "<b>How many different players</b> went hunting?",
      "hint": "Count the different player_id values."
     },
     "es": {
      "idea": "COUNT(DISTINCT)",
      "lesson": "<code>COUNT(DISTINCT columna)</code> cuenta cuántos valores <b>distintos</b> hay.",
      "task": "¿<b>Cuántos jugadores distintos</b> salieron a cazar?",
      "hint": "Cuenta los valores distintos de player_id."
     },
     "de": {
      "idea": "COUNT(DISTINCT)",
      "lesson": "<code>COUNT(DISTINCT spalte)</code> zählt, wie viele <b>verschiedene</b> Werte es gibt.",
      "task": "<b>Wie viele verschiedene Spieler</b> waren jagen?",
      "hint": "Zähl die verschiedenen player_id-Werte."
     }
    },
    "unlock": {
     "items": [
      6
     ]
    }
   },
   {
    "answer": "SELECT SUM(xp) FROM hunts WHERE biome = 'nether'",
    "example": "SELECT COUNT(*) FROM hunts WHERE day = 3",
    "text": {
     "en": {
      "idea": "Totals with a rule",
      "lesson": "WHERE works together with SUM and COUNT: first the rows are filtered, then they're added up.",
      "task": "How much <b>XP</b> was earned in the <b>nether</b>?",
      "hint": "SUM(xp) … WHERE biome = 'nether'"
     },
     "es": {
      "idea": "Totales con una regla",
      "lesson": "WHERE funciona junto con SUM y COUNT: primero se filtran las filas, luego se suman.",
      "task": "¿Cuánta <b>XP</b> se ganó en el <b>nether</b>?",
      "hint": "SUM(xp) … WHERE biome = 'nether'"
     },
     "de": {
      "idea": "Summen mit Regel",
      "lesson": "WHERE klappt zusammen mit SUM und COUNT: Erst werden die Zeilen gefiltert, dann zusammengezählt.",
      "task": "Wie viel <b>XP</b> wurde im <b>nether</b> verdient?",
      "hint": "SUM(xp) … WHERE biome = 'nether'"
     }
    },
    "unlock": {
     "items": [
      7
     ]
    }
   }
  ]
 },
 {
  "id": "sq4",
  "tables": [
   "hunts"
  ],
  "text": {
   "en": {
    "title": "Village Report",
    "story": "The village elder wants a report — not one big total, but <b>one line per player, per day, per biome</b>. That's what <code>GROUP BY</code> is for: the most important tool in data analysis."
   },
   "es": {
    "title": "Informe de la aldea",
    "story": "El anciano de la aldea quiere un informe — no un solo total, sino <b>una línea por jugador, por día, por bioma</b>. Para eso sirve <code>GROUP BY</code>: la herramienta más importante del análisis de datos."
   },
   "de": {
    "title": "Dorfbericht",
    "story": "Der Dorfälteste will einen Bericht — nicht eine große Summe, sondern <b>eine Zeile pro Spieler, pro Tag, pro Biom</b>. Dafür gibt es <code>GROUP BY</code>: das wichtigste Werkzeug der Datenanalyse."
   }
  },
  "quests": [
   {
    "answer": "SELECT biome, COUNT(*) FROM hunts GROUP BY biome",
    "example": "SELECT type, COUNT(*) FROM mobs GROUP BY type",
    "text": {
     "en": {
      "idea": "GROUP BY",
      "lesson": "<code>GROUP BY biome</code> puts rows with the same biome together and gives you <b>one row per group</b>. COUNT, SUM and AVG then work <b>inside each group</b>. Put the group column in the SELECT too, so you can see which group is which.",
      "task": "Show each <b>biome</b> and <b>how many hunts</b> happened there.",
      "hint": "SELECT biome, COUNT(*) … GROUP BY biome"
     },
     "es": {
      "idea": "GROUP BY",
      "lesson": "<code>GROUP BY biome</code> junta las filas con el mismo bioma y te da <b>una fila por grupo</b>. COUNT, SUM y AVG trabajan entonces <b>dentro de cada grupo</b>. Pon también la columna del grupo en el SELECT, para ver qué grupo es cuál.",
      "task": "Muestra cada <b>biome</b> y <b>cuántas cacerías</b> hubo allí.",
      "hint": "SELECT biome, COUNT(*) … GROUP BY biome"
     },
     "de": {
      "idea": "GROUP BY",
      "lesson": "<code>GROUP BY biome</code> packt Zeilen mit demselben Biom zusammen und gibt dir <b>eine Zeile pro Gruppe</b>. COUNT, SUM und AVG rechnen dann <b>in jeder Gruppe</b>. Schreib die Gruppenspalte auch ins SELECT, damit du siehst, welche Gruppe welche ist.",
      "task": "Zeig jedes <b>biome</b> und <b>wie viele Jagden</b> dort waren.",
      "hint": "SELECT biome, COUNT(*) … GROUP BY biome"
     }
    },
    "unlock": {
     "items": [
      8
     ]
    }
   },
   {
    "answer": "SELECT player_id, SUM(xp) AS total FROM hunts GROUP BY player_id ORDER BY total DESC",
    "example": "SELECT home, SUM(health) AS total FROM mobs GROUP BY home ORDER BY total DESC",
    "text": {
     "en": {
      "idea": "Sort by a total",
      "lesson": "Give the total a name with <code>AS</code>, then you can sort by that name: <code>ORDER BY total DESC</code>.",
      "task": "Show each <b>player_id</b> and their <b>total XP</b>, best player first.",
      "hint": "SUM(xp) AS total, GROUP BY player_id, then ORDER BY total DESC."
     },
     "es": {
      "idea": "Ordenar por un total",
      "lesson": "Ponle nombre al total con <code>AS</code> y luego podrás ordenar por ese nombre: <code>ORDER BY total DESC</code>.",
      "task": "Muestra cada <b>player_id</b> y su <b>XP total</b>, el mejor primero.",
      "hint": "SUM(xp) AS total, GROUP BY player_id y luego ORDER BY total DESC."
     },
     "de": {
      "idea": "Nach einer Summe sortieren",
      "lesson": "Gib der Summe mit <code>AS</code> einen Namen, dann kannst du danach sortieren: <code>ORDER BY total DESC</code>.",
      "task": "Zeig jede <b>player_id</b> und ihre <b>gesamte XP</b>, der beste Spieler zuerst.",
      "hint": "SUM(xp) AS total, GROUP BY player_id, dann ORDER BY total DESC."
     }
    },
    "orderCol": 1,
    "unlock": {
     "items": [
      9
     ]
    }
   },
   {
    "answer": "SELECT player_id, biome, COUNT(*) FROM hunts GROUP BY player_id, biome",
    "example": "SELECT type, home, COUNT(*) FROM mobs GROUP BY type, home",
    "text": {
     "en": {
      "idea": "Group by 2 columns",
      "lesson": "You can group by several columns: <code>GROUP BY a, b</code> makes one row for every <b>combination</b> of a and b.",
      "task": "How many hunts did each <b>player_id</b> have in each <b>biome</b>?",
      "hint": "GROUP BY player_id, biome"
     },
     "es": {
      "idea": "Agrupar por 2 columnas",
      "lesson": "Puedes agrupar por varias columnas: <code>GROUP BY a, b</code> crea una fila por cada <b>combinación</b> de a y b.",
      "task": "¿Cuántas cacerías tuvo cada <b>player_id</b> en cada <b>biome</b>?",
      "hint": "GROUP BY player_id, biome"
     },
     "de": {
      "idea": "Nach 2 Spalten gruppieren",
      "lesson": "Du kannst nach mehreren Spalten gruppieren: <code>GROUP BY a, b</code> macht eine Zeile für jede <b>Kombination</b> aus a und b.",
      "task": "Wie viele Jagden hatte jede <b>player_id</b> in jedem <b>biome</b>?",
      "hint": "GROUP BY player_id, biome"
     }
    },
    "unlock": {
     "items": [
      10
     ]
    }
   },
   {
    "answer": "SELECT day, COUNT(*) FROM hunts GROUP BY day HAVING COUNT(*) > 6",
    "example": "SELECT home, COUNT(*) FROM mobs GROUP BY home HAVING COUNT(*) > 2",
    "text": {
     "en": {
      "idea": "HAVING",
      "lesson": "<code>WHERE</code> filters single rows <b>before</b> grouping. To filter whole <b>groups</b> (for example by their COUNT), use <code>HAVING</code> after GROUP BY.",
      "task": "Which <b>days</b> had <b>more than 6 hunts</b>? Show the day and its count.",
      "hint": "GROUP BY day HAVING COUNT(*) > 6"
     },
     "es": {
      "idea": "HAVING",
      "lesson": "<code>WHERE</code> filtra filas sueltas <b>antes</b> de agrupar. Para filtrar <b>grupos</b> enteros (por ejemplo por su COUNT), usa <code>HAVING</code> después de GROUP BY.",
      "task": "¿Qué <b>días</b> tuvieron <b>más de 6 cacerías</b>? Muestra el día y su número.",
      "hint": "GROUP BY day HAVING COUNT(*) > 6"
     },
     "de": {
      "idea": "HAVING",
      "lesson": "<code>WHERE</code> filtert einzelne Zeilen <b>vor</b> dem Gruppieren. Um ganze <b>Gruppen</b> zu filtern (zum Beispiel nach ihrem COUNT), nimm <code>HAVING</code> nach GROUP BY.",
      "task": "An welchen <b>Tagen</b> gab es <b>mehr als 6 Jagden</b>? Zeig den Tag und die Anzahl.",
      "hint": "GROUP BY day HAVING COUNT(*) > 6"
     }
    },
    "unlock": {
     "items": [
      11
     ]
    }
   },
   {
    "answer": "SELECT player_id, SUM(xp) FROM hunts WHERE biome = 'nether' GROUP BY player_id HAVING SUM(xp) > 30",
    "example": "SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT …",
    "text": {
     "en": {
      "idea": "The full order",
      "lesson": "The parts always come in this order: <code>SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT</code>. WHERE picks rows, GROUP BY groups them, HAVING picks groups.",
      "task": "In the <b>nether</b> only: show each <b>player_id</b> and their total <b>XP</b> — but only players with <b>more than 30</b> XP there.",
      "hint": "WHERE biome = 'nether' comes before GROUP BY; HAVING SUM(xp) > 30 comes after it."
     },
     "es": {
      "idea": "El orden completo",
      "lesson": "Las partes van siempre en este orden: <code>SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT</code>. WHERE elige filas, GROUP BY las agrupa, HAVING elige grupos.",
      "task": "Solo en el <b>nether</b>: muestra cada <b>player_id</b> y su <b>XP</b> total — pero solo los jugadores con <b>más de 30</b> XP allí.",
      "hint": "WHERE biome = 'nether' va antes de GROUP BY; HAVING SUM(xp) > 30 va después."
     },
     "de": {
      "idea": "Die ganze Reihenfolge",
      "lesson": "Die Teile kommen immer in dieser Reihenfolge: <code>SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT</code>. WHERE wählt Zeilen, GROUP BY gruppiert sie, HAVING wählt Gruppen.",
      "task": "Nur im <b>nether</b>: Zeig jede <b>player_id</b> und ihre gesamte <b>XP</b> — aber nur Spieler mit <b>mehr als 30</b> XP dort.",
      "hint": "WHERE biome = 'nether' kommt vor GROUP BY; HAVING SUM(xp) > 30 danach."
     }
    },
    "unlock": {
     "items": [
      12
     ]
    }
   }
  ]
 },
 {
  "id": "sq5",
  "tables": [
   "mobs",
   "hunts"
  ],
  "text": {
   "en": {
    "title": "Label Maker",
    "story": "Numbers are great, but new players want simple words: is this mob <i>dangerous</i>? Was that a <i>big</i> hunt? Time to make <b>your own columns</b>."
   },
   "es": {
    "title": "Fábrica de etiquetas",
    "story": "Los números están bien, pero los jugadores nuevos quieren palabras sencillas: ¿esta criatura es <i>peligrosa</i>? ¿Fue una cacería <i>grande</i>? Es hora de crear <b>tus propias columnas</b>."
   },
   "de": {
    "title": "Etiketten-Werkstatt",
    "story": "Zahlen sind toll, aber neue Spieler wollen einfache Wörter: Ist dieser Mob <i>gefährlich</i>? War das eine <i>große</i> Jagd? Zeit für <b>deine eigenen Spalten</b>."
   }
  },
  "quests": [
   {
    "answer": "SELECT name, CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END FROM mobs",
    "example": "SELECT name,\n  CASE WHEN health > 50 THEN 'big' ELSE 'small' END AS size\nFROM mobs",
    "text": {
     "en": {
      "idea": "CASE WHEN",
      "lesson": "<code>CASE WHEN rule THEN value ELSE other END</code> is SQL's \"if\". It makes a <b>new column</b> with a value for every row. Don't forget the <code>END</code>!",
      "task": "Show every mob's <b>name</b> and a label: <code>'danger'</code> if its damage is <b>more than 10</b>, otherwise <code>'safe'</code>.",
      "hint": "CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END"
     },
     "es": {
      "idea": "CASE WHEN",
      "lesson": "<code>CASE WHEN regla THEN valor ELSE otro END</code> es el \"si\" de SQL. Crea una <b>columna nueva</b> con un valor para cada fila. ¡No olvides el <code>END</code>!",
      "task": "Muestra el <b>name</b> de cada criatura y una etiqueta: <code>'danger'</code> si su daño es <b>mayor que 10</b>, si no <code>'safe'</code>.",
      "hint": "CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END"
     },
     "de": {
      "idea": "CASE WHEN",
      "lesson": "<code>CASE WHEN regel THEN wert ELSE anderer END</code> ist das \"wenn\" von SQL. Es macht eine <b>neue Spalte</b> mit einem Wert für jede Zeile. Vergiss das <code>END</code> nicht!",
      "task": "Zeig den <b>name</b> jedes Mobs und ein Etikett: <code>'danger'</code>, wenn sein Schaden <b>größer als 10</b> ist, sonst <code>'safe'</code>.",
      "hint": "CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END"
     }
    },
    "freeNames": true,
    "unlock": {
     "items": [
      13
     ]
    }
   },
   {
    "answer": "SELECT name, CASE WHEN damage >= 20 THEN 'boss' WHEN damage >= 5 THEN 'fighter' ELSE 'harmless' END FROM mobs",
    "example": "CASE WHEN health >= 100 THEN 'giant'\n     WHEN health >= 20 THEN 'strong'\n     ELSE 'weak' END",
    "text": {
     "en": {
      "idea": "Several WHENs",
      "lesson": "You can stack WHENs. SQL checks them <b>from top to bottom</b> and uses the <b>first</b> one that is true — so put the strictest rule first.",
      "task": "Show <b>name</b> and a rank: <code>'boss'</code> if damage is <b>20 or more</b>, <code>'fighter'</code> if damage is <b>5 or more</b>, otherwise <code>'harmless'</code>.",
      "hint": "First WHEN damage >= 20, then WHEN damage >= 5, then ELSE."
     },
     "es": {
      "idea": "Varios WHEN",
      "lesson": "Puedes poner varios WHEN. SQL los revisa <b>de arriba abajo</b> y usa el <b>primero</b> que sea cierto — así que pon primero la regla más estricta.",
      "task": "Muestra <b>name</b> y un rango: <code>'boss'</code> si el daño es <b>20 o más</b>, <code>'fighter'</code> si es <b>5 o más</b>, si no <code>'harmless'</code>.",
      "hint": "Primero WHEN damage >= 20, luego WHEN damage >= 5, luego ELSE."
     },
     "de": {
      "idea": "Mehrere WHENs",
      "lesson": "Du kannst mehrere WHENs stapeln. SQL prüft sie <b>von oben nach unten</b> und nimmt das <b>erste</b>, das stimmt — also kommt die strengste Regel zuerst.",
      "task": "Zeig <b>name</b> und einen Rang: <code>'boss'</code> bei Schaden <b>20 oder mehr</b>, <code>'fighter'</code> bei <b>5 oder mehr</b>, sonst <code>'harmless'</code>.",
      "hint": "Zuerst WHEN damage >= 20, dann WHEN damage >= 5, dann ELSE."
     }
    },
    "freeNames": true,
    "unlock": {
     "items": [
      14
     ]
    }
   },
   {
    "answer": "SELECT UPPER(name), LENGTH(name) FROM mobs",
    "example": "SELECT LOWER(name), LENGTH(home) FROM mobs",
    "text": {
     "en": {
      "idea": "Text functions",
      "lesson": "<code>UPPER(text)</code> makes CAPITALS, <code>LOWER(text)</code> small letters, <code>LENGTH(text)</code> counts the letters.",
      "task": "Show every mob's name in <b>CAPITALS</b> and <b>how many letters</b> its name has.",
      "hint": "UPPER(name), LENGTH(name)"
     },
     "es": {
      "idea": "Funciones de texto",
      "lesson": "<code>UPPER(texto)</code> pone MAYÚSCULAS, <code>LOWER(texto)</code> minúsculas, <code>LENGTH(texto)</code> cuenta las letras.",
      "task": "Muestra el nombre de cada criatura en <b>MAYÚSCULAS</b> y <b>cuántas letras</b> tiene.",
      "hint": "UPPER(name), LENGTH(name)"
     },
     "de": {
      "idea": "Textfunktionen",
      "lesson": "<code>UPPER(text)</code> macht GROSSBUCHSTABEN, <code>LOWER(text)</code> kleine, <code>LENGTH(text)</code> zählt die Buchstaben.",
      "task": "Zeig den Namen jedes Mobs in <b>GROSSBUCHSTABEN</b> und <b>wie viele Buchstaben</b> er hat.",
      "hint": "UPPER(name), LENGTH(name)"
     }
    },
    "freeNames": true,
    "unlock": {
     "items": [
      15
     ]
    }
   },
   {
    "answer": "SELECT name || ' lives in the ' || home FROM mobs",
    "example": "SELECT name || ' drops ' || loot FROM mobs",
    "text": {
     "en": {
      "idea": "Glue text with ||",
      "lesson": "<code>||</code> glues pieces of text together. Mix columns with your own text in quotes — and don't forget the spaces!",
      "task": "Make a sentence for every mob, like <code>Creeper lives in the overworld</code>.",
      "hint": "name || ' lives in the ' || home"
     },
     "es": {
      "idea": "Pegar texto con ||",
      "lesson": "<code>||</code> pega trozos de texto. Mezcla columnas con tu propio texto entre comillas — ¡y no olvides los espacios!",
      "task": "Haz una frase para cada criatura, como <code>Creeper lives in the overworld</code>.",
      "hint": "name || ' lives in the ' || home"
     },
     "de": {
      "idea": "Text kleben mit ||",
      "lesson": "<code>||</code> klebt Textstücke zusammen. Misch Spalten mit eigenem Text in Anführungszeichen — und vergiss die Leerzeichen nicht!",
      "task": "Bau für jeden Mob einen Satz, zum Beispiel <code>Creeper lives in the overworld</code>.",
      "hint": "name || ' lives in the ' || home"
     }
    },
    "freeNames": true,
    "unlock": {
     "items": [
      16
     ]
    }
   },
   {
    "answer": "SELECT CASE WHEN xp >= 10 THEN 'big' ELSE 'small' END AS size, COUNT(*) FROM hunts GROUP BY size",
    "example": "SELECT CASE WHEN health >= 20 THEN 'tank' ELSE 'squishy' END AS size,\n  COUNT(*)\nFROM mobs GROUP BY size",
    "text": {
     "en": {
      "idea": "Group by your label",
      "lesson": "A CASE column can be grouped like any other column. Name it with <code>AS</code>, then <code>GROUP BY</code> that name.",
      "task": "Label each hunt <code>'big'</code> if it gave <b>10 XP or more</b>, otherwise <code>'small'</code>. Count how many hunts are big and how many are small.",
      "hint": "CASE … END AS size, COUNT(*) … GROUP BY size"
     },
     "es": {
      "idea": "Agrupar por tu etiqueta",
      "lesson": "Una columna CASE se puede agrupar como cualquier otra. Ponle nombre con <code>AS</code> y luego haz <code>GROUP BY</code> con ese nombre.",
      "task": "Etiqueta cada cacería como <code>'big'</code> si dio <b>10 XP o más</b>, si no <code>'small'</code>. Cuenta cuántas son big y cuántas small.",
      "hint": "CASE … END AS size, COUNT(*) … GROUP BY size"
     },
     "de": {
      "idea": "Nach deinem Etikett gruppieren",
      "lesson": "Eine CASE-Spalte kann man gruppieren wie jede andere. Gib ihr mit <code>AS</code> einen Namen, dann <code>GROUP BY</code> mit diesem Namen.",
      "task": "Nenn jede Jagd <code>'big'</code>, wenn sie <b>10 XP oder mehr</b> gebracht hat, sonst <code>'small'</code>. Zähl, wie viele big und wie viele small sind.",
      "hint": "CASE … END AS size, COUNT(*) … GROUP BY size"
     }
    },
    "freeNames": true
   }
  ]
 },
 {
  "id": "sq6",
  "tables": [
   "hunts",
   "players",
   "mobs",
   "items"
  ],
  "text": {
   "en": {
    "title": "Connect the Tables",
    "story": "The hunt log only has numbers like <code>player_id = 3</code>. Who is player 3? Which mob is <code>mob_id = 6</code>? The answers are in other tables — and <code>JOIN</code> connects them. This is the superpower of SQL."
   },
   "es": {
    "title": "Conecta las tablas",
    "story": "El registro de cacerías solo tiene números como <code>player_id = 3</code>. ¿Quién es el jugador 3? ¿Qué criatura es <code>mob_id = 6</code>? Las respuestas están en otras tablas — y <code>JOIN</code> las conecta. Es el superpoder de SQL."
   },
   "de": {
    "title": "Tabellen verbinden",
    "story": "Im Jagdbuch stehen nur Zahlen wie <code>player_id = 3</code>. Wer ist Spieler 3? Welcher Mob ist <code>mob_id = 6</code>? Die Antworten stehen in anderen Tabellen — und <code>JOIN</code> verbindet sie. Das ist die Superkraft von SQL."
   }
  },
  "quests": [
   {
    "answer": "DESCRIBE players",
    "example": "SHOW TABLES",
    "text": {
     "en": {
      "idea": "Find the matching columns",
      "lesson": "<code>SHOW TABLES</code> lists every table. To connect two tables you need a column in one that <b>matches</b> a column in the other — so describe them and look for the match: <code>hunts.player_id</code> ↔ <code>players.id</code>.",
      "task": "<b>Describe</b> the <code>players</code> table. Which of its columns could match <code>hunts.player_id</code>?",
      "hint": "DESCRIBE players"
     },
     "es": {
      "idea": "Encuentra las columnas que coinciden",
      "lesson": "<code>SHOW TABLES</code> muestra todas las tablas. Para conectar dos tablas necesitas una columna en una que <b>coincida</b> con una columna de la otra — así que descríbelas y busca la pareja: <code>hunts.player_id</code> ↔ <code>players.id</code>.",
      "task": "<b>Describe</b> la tabla <code>players</code>. ¿Qué columna suya podría coincidir con <code>hunts.player_id</code>?",
      "hint": "DESCRIBE players"
     },
     "de": {
      "idea": "Finde die passenden Spalten",
      "lesson": "<code>SHOW TABLES</code> listet alle Tabellen. Um zwei Tabellen zu verbinden, brauchst du eine Spalte in der einen, die zu einer Spalte in der anderen <b>passt</b> — also beschreib sie und such das Paar: <code>hunts.player_id</code> ↔ <code>players.id</code>.",
      "task": "<b>Beschreib</b> die Tabelle <code>players</code>. Welche ihrer Spalten könnte zu <code>hunts.player_id</code> passen?",
      "hint": "DESCRIBE players"
     }
    }
   },
   {
    "answer": "SELECT hunts.day, mobs.name FROM hunts JOIN mobs ON hunts.mob_id = mobs.id",
    "example": "SELECT hunts.day, players.name\nFROM hunts\nJOIN players ON hunts.player_id = players.id",
    "text": {
     "en": {
      "idea": "JOIN … ON",
      "lesson": "<code>JOIN</code> puts two tables side by side. <code>ON</code> says which columns must match: <code>hunts.mob_id = mobs.id</code>. When both tables have a column with the same name, write <code>table.column</code>.",
      "task": "Show the <b>day</b> of every hunt and the <b>name of the mob</b> that was hunted.",
      "hint": "JOIN mobs ON hunts.mob_id = mobs.id, then SELECT hunts.day, mobs.name"
     },
     "es": {
      "idea": "JOIN … ON",
      "lesson": "<code>JOIN</code> pone dos tablas lado a lado. <code>ON</code> dice qué columnas deben coincidir: <code>hunts.mob_id = mobs.id</code>. Si las dos tablas tienen una columna con el mismo nombre, escribe <code>tabla.columna</code>.",
      "task": "Muestra el <b>day</b> de cada cacería y el <b>nombre de la criatura</b> cazada.",
      "hint": "JOIN mobs ON hunts.mob_id = mobs.id, luego SELECT hunts.day, mobs.name"
     },
     "de": {
      "idea": "JOIN … ON",
      "lesson": "<code>JOIN</code> stellt zwei Tabellen nebeneinander. <code>ON</code> sagt, welche Spalten zusammenpassen müssen: <code>hunts.mob_id = mobs.id</code>. Haben beide Tabellen eine Spalte mit gleichem Namen, schreib <code>tabelle.spalte</code>.",
      "task": "Zeig den <b>day</b> jeder Jagd und den <b>Namen des Mobs</b>, der gejagt wurde.",
      "hint": "JOIN mobs ON hunts.mob_id = mobs.id, dann SELECT hunts.day, mobs.name"
     }
    }
   },
   {
    "answer": "SELECT p.name, h.xp FROM hunts h JOIN players p ON h.player_id = p.id",
    "example": "SELECT h.day, m.name\nFROM hunts h\nJOIN mobs m ON h.mob_id = m.id",
    "text": {
     "en": {
      "idea": "Short table names",
      "lesson": "Writing <code>hunts.</code> again and again is long. Give a table a short name right after it: <code>FROM hunts h JOIN players p</code>. Then write <code>h.xp</code>, <code>p.name</code>.",
      "task": "Show each <b>player's name</b> and the <b>XP</b> of each of their hunts.",
      "hint": "FROM hunts h JOIN players p ON h.player_id = p.id"
     },
     "es": {
      "idea": "Nombres cortos de tabla",
      "lesson": "Escribir <code>hunts.</code> una y otra vez es largo. Dale a la tabla un nombre corto justo detrás: <code>FROM hunts h JOIN players p</code>. Luego escribe <code>h.xp</code>, <code>p.name</code>.",
      "task": "Muestra el <b>nombre de cada jugador</b> y la <b>XP</b> de cada una de sus cacerías.",
      "hint": "FROM hunts h JOIN players p ON h.player_id = p.id"
     },
     "de": {
      "idea": "Kurze Tabellennamen",
      "lesson": "Immer wieder <code>hunts.</code> zu schreiben ist lang. Gib einer Tabelle direkt dahinter einen kurzen Namen: <code>FROM hunts h JOIN players p</code>. Dann schreibst du <code>h.xp</code>, <code>p.name</code>.",
      "task": "Zeig den <b>Namen jedes Spielers</b> und die <b>XP</b> jeder seiner Jagden.",
      "hint": "FROM hunts h JOIN players p ON h.player_id = p.id"
     }
    }
   },
   {
    "answer": "SELECT p.name, SUM(h.xp) AS total FROM hunts h JOIN players p ON h.player_id = p.id GROUP BY p.name ORDER BY total DESC",
    "example": "SELECT m.type, COUNT(*)\nFROM hunts h JOIN mobs m ON h.mob_id = m.id\nGROUP BY m.type",
    "text": {
     "en": {
      "idea": "JOIN + GROUP BY",
      "lesson": "Everything you learned still works after a JOIN: WHERE, GROUP BY, ORDER BY…",
      "task": "Make a <b>leaderboard</b>: each <b>player name</b> with their <b>total XP</b>, best first.",
      "hint": "JOIN players, GROUP BY p.name, SUM(h.xp) AS total, ORDER BY total DESC"
     },
     "es": {
      "idea": "JOIN + GROUP BY",
      "lesson": "Todo lo que aprendiste sigue funcionando después de un JOIN: WHERE, GROUP BY, ORDER BY…",
      "task": "Haz una <b>clasificación</b>: el <b>nombre de cada jugador</b> con su <b>XP total</b>, el mejor primero.",
      "hint": "JOIN players, GROUP BY p.name, SUM(h.xp) AS total, ORDER BY total DESC"
     },
     "de": {
      "idea": "JOIN + GROUP BY",
      "lesson": "Alles, was du gelernt hast, klappt auch nach einem JOIN: WHERE, GROUP BY, ORDER BY…",
      "task": "Mach eine <b>Bestenliste</b>: jeder <b>Spielername</b> mit seiner <b>gesamten XP</b>, der Beste zuerst.",
      "hint": "JOIN players, GROUP BY p.name, SUM(h.xp) AS total, ORDER BY total DESC"
     }
    },
    "orderCol": 1
   },
   {
    "answer": "SELECT m.name, i.value FROM mobs m JOIN items i ON m.loot = i.name",
    "example": "SELECT m.name, i.rarity\nFROM mobs m JOIN items i ON m.loot = i.name",
    "text": {
     "en": {
      "idea": "Join on text",
      "lesson": "The matching columns don't have to be ids. Every mob's <code>loot</code> is the <code>name</code> of an item.",
      "task": "Show each mob's <b>name</b> and how many <b>emeralds</b> its loot is worth (<code>value</code>).",
      "hint": "JOIN items i ON m.loot = i.name, then SELECT m.name, i.value"
     },
     "es": {
      "idea": "Unir por texto",
      "lesson": "Las columnas que coinciden no tienen que ser ids. El <code>loot</code> de cada criatura es el <code>name</code> de un objeto.",
      "task": "Muestra el <b>name</b> de cada criatura y cuántas <b>esmeraldas</b> vale su botín (<code>value</code>).",
      "hint": "JOIN items i ON m.loot = i.name, luego SELECT m.name, i.value"
     },
     "de": {
      "idea": "Über Text verbinden",
      "lesson": "Die passenden Spalten müssen keine ids sein. Der <code>loot</code> jedes Mobs ist der <code>name</code> eines Gegenstands.",
      "task": "Zeig den <b>name</b> jedes Mobs und wie viele <b>Smaragde</b> seine Beute wert ist (<code>value</code>).",
      "hint": "JOIN items i ON m.loot = i.name, dann SELECT m.name, i.value"
     }
    }
   },
   {
    "answer": "SELECT p.name FROM players p LEFT JOIN hunts h ON p.id = h.player_id WHERE h.id IS NULL",
    "example": "SELECT m.name, i.value\nFROM mobs m LEFT JOIN items i ON m.loot = i.name",
    "text": {
     "en": {
      "idea": "LEFT JOIN",
      "lesson": "A normal JOIN <b>drops</b> rows without a match. <code>LEFT JOIN</code> keeps <b>every</b> row of the first table; where nothing matches, the other table's columns are <code>NULL</code>.",
      "task": "One player has <b>never been hunting</b>. Find their <b>name</b>.",
      "hint": "players p LEFT JOIN hunts h ON p.id = h.player_id … WHERE h.id IS NULL"
     },
     "es": {
      "idea": "LEFT JOIN",
      "lesson": "Un JOIN normal <b>quita</b> las filas sin pareja. <code>LEFT JOIN</code> mantiene <b>todas</b> las filas de la primera tabla; donde no hay coincidencia, las columnas de la otra tabla son <code>NULL</code>.",
      "task": "Un jugador <b>nunca ha ido de caza</b>. Encuentra su <b>nombre</b>.",
      "hint": "players p LEFT JOIN hunts h ON p.id = h.player_id … WHERE h.id IS NULL"
     },
     "de": {
      "idea": "LEFT JOIN",
      "lesson": "Ein normaler JOIN <b>wirft</b> Zeilen ohne Partner raus. <code>LEFT JOIN</code> behält <b>jede</b> Zeile der ersten Tabelle; wo nichts passt, sind die Spalten der anderen Tabelle <code>NULL</code>.",
      "task": "Ein Spieler war <b>noch nie jagen</b>. Finde seinen <b>Namen</b>.",
      "hint": "players p LEFT JOIN hunts h ON p.id = h.player_id … WHERE h.id IS NULL"
     }
    }
   },
   {
    "answer": "SELECT p.name, COUNT(*) FROM hunts h JOIN players p ON h.player_id = p.id JOIN mobs m ON h.mob_id = m.id WHERE m.type = 'hostile' GROUP BY p.name ORDER BY COUNT(*) DESC",
    "example": "SELECT p.name, m.name\nFROM hunts h\nJOIN players p ON h.player_id = p.id\nJOIN mobs m ON h.mob_id = m.id",
    "text": {
     "en": {
      "idea": "Three tables",
      "lesson": "You can JOIN again and again: <code>FROM hunts h JOIN players p ON … JOIN mobs m ON …</code>",
      "task": "Who hunts the most <b>hostile</b> mobs? Show each <b>player name</b> and how many hostile mobs they hunted, most first.",
      "hint": "Join players and mobs, WHERE m.type = 'hostile', GROUP BY p.name, ORDER BY COUNT(*) DESC"
     },
     "es": {
      "idea": "Tres tablas",
      "lesson": "Puedes hacer JOIN una y otra vez: <code>FROM hunts h JOIN players p ON … JOIN mobs m ON …</code>",
      "task": "¿Quién caza más criaturas <b>hostile</b>? Muestra el <b>nombre de cada jugador</b> y cuántas hostiles cazó, de más a menos.",
      "hint": "Une players y mobs, WHERE m.type = 'hostile', GROUP BY p.name, ORDER BY COUNT(*) DESC"
     },
     "de": {
      "idea": "Drei Tabellen",
      "lesson": "Du kannst immer weiter JOINen: <code>FROM hunts h JOIN players p ON … JOIN mobs m ON …</code>",
      "task": "Wer jagt die meisten <b>hostile</b> Mobs? Zeig jeden <b>Spielernamen</b> und wie viele feindliche Mobs er gejagt hat, die meisten zuerst.",
      "hint": "Verbinde players und mobs, WHERE m.type = 'hostile', GROUP BY p.name, ORDER BY COUNT(*) DESC"
     }
    },
    "orderCol": 1
   }
  ]
 },
 {
  "id": "sq7",
  "tables": [
   "chest_log",
   "trades",
   "players",
   "items"
  ],
  "text": {
   "en": {
    "title": "Boss: The Diamond Thief",
    "story": "Boss case! 🕵️ On day 8, Steve put <b>12 diamonds</b> in the village chest. On the morning of day 10 the chest was <b>empty</b>. Two new tables hold the clues: <code>chest_log</code> (who used the chest, when, and what they put in or took out) and <code>trades</code> (what players sold to the wandering trader). Solve it step by step."
   },
   "es": {
    "title": "Jefe: el ladrón de diamantes",
    "story": "¡Caso jefe! 🕵️ El día 8, Steve guardó <b>12 diamantes</b> en el cofre de la aldea. La mañana del día 10 el cofre estaba <b>vacío</b>. Dos tablas nuevas tienen las pistas: <code>chest_log</code> (quién usó el cofre, cuándo, y qué metió o sacó) y <code>trades</code> (qué vendieron los jugadores al comerciante). Resuélvelo paso a paso."
   },
   "de": {
    "title": "Boss: Der Diamantendieb",
    "story": "Boss-Fall! 🕵️ An Tag 8 hat Steve <b>12 Diamanten</b> in die Dorftruhe gelegt. Am Morgen von Tag 10 war die Truhe <b>leer</b>. Zwei neue Tabellen enthalten die Hinweise: <code>chest_log</code> (wer die Truhe wann benutzt hat und was er hineingelegt oder herausgenommen hat) und <code>trades</code> (was Spieler dem Händler verkauft haben). Lös den Fall Schritt für Schritt."
   }
  },
  "quests": [
   {
    "answer": "DESCRIBE chest_log",
    "example": "SHOW TABLES",
    "text": {
     "en": {
      "idea": "Clue 0: the evidence",
      "lesson": "A good detective first checks <b>what evidence exists</b>. There are two new tables in this case: <code>chest_log</code> and <code>trades</code>.",
      "task": "<b>Describe</b> the <code>chest_log</code> table to see what the village wrote down about the chest.",
      "hint": "DESCRIBE chest_log"
     },
     "es": {
      "idea": "Pista 0: las pruebas",
      "lesson": "Un buen detective primero mira <b>qué pruebas hay</b>. En este caso hay dos tablas nuevas: <code>chest_log</code> y <code>trades</code>.",
      "task": "<b>Describe</b> la tabla <code>chest_log</code> para ver qué apuntó la aldea sobre el cofre.",
      "hint": "DESCRIBE chest_log"
     },
     "de": {
      "idea": "Hinweis 0: die Beweise",
      "lesson": "Ein guter Detektiv schaut zuerst, <b>welche Beweise es gibt</b>. In diesem Fall gibt es zwei neue Tabellen: <code>chest_log</code> und <code>trades</code>.",
      "task": "<b>Beschreib</b> die Tabelle <code>chest_log</code>, um zu sehen, was das Dorf über die Truhe aufgeschrieben hat.",
      "hint": "DESCRIBE chest_log"
     }
    }
   },
   {
    "answer": "SELECT * FROM chest_log WHERE item = 'diamond' ORDER BY day, hour",
    "example": "SELECT * FROM hunts ORDER BY day, xp DESC",
    "text": {
     "en": {
      "idea": "Clue 1: the chest",
      "lesson": "Detectives start with the facts. You can sort by two columns: <code>ORDER BY day, hour</code> sorts by day first, then by hour.",
      "task": "Show every row of <code>chest_log</code> about <b>diamonds</b>, in time order (<b>day</b>, then <b>hour</b>). How many diamonds are missing?",
      "hint": "WHERE item = 'diamond' ORDER BY day, hour"
     },
     "es": {
      "idea": "Pista 1: el cofre",
      "lesson": "Los detectives empiezan por los hechos. Puedes ordenar por dos columnas: <code>ORDER BY day, hour</code> ordena primero por día y luego por hora.",
      "task": "Muestra cada fila de <code>chest_log</code> sobre <b>diamantes</b>, en orden de tiempo (<b>day</b> y luego <b>hour</b>). ¿Cuántos diamantes faltan?",
      "hint": "WHERE item = 'diamond' ORDER BY day, hour"
     },
     "de": {
      "idea": "Hinweis 1: die Truhe",
      "lesson": "Detektive fangen mit den Fakten an. Du kannst nach zwei Spalten sortieren: <code>ORDER BY day, hour</code> sortiert zuerst nach Tag, dann nach Stunde.",
      "task": "Zeig jede Zeile aus <code>chest_log</code> über <b>Diamanten</b>, zeitlich sortiert (<b>day</b>, dann <b>hour</b>). Wie viele Diamanten fehlen?",
      "hint": "WHERE item = 'diamond' ORDER BY day, hour"
     }
    },
    "orderCol": 1
   },
   {
    "answer": "SELECT p.name, c.hour FROM chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20",
    "example": null,
    "text": {
     "en": {
      "idea": "Clue 2: night visitors",
      "lesson": "The chest was fine on the evening of day 9. Who came at night? Use a JOIN to turn player_ids into names.",
      "task": "Show the <b>name</b> and <b>hour</b> of everyone who used the chest on <b>day 9</b> at <b>20:00 or later</b>. These are your suspects.",
      "hint": "chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20"
     },
     "es": {
      "idea": "Pista 2: visitas nocturnas",
      "lesson": "La tarde del día 9 el cofre estaba bien. ¿Quién vino de noche? Usa un JOIN para cambiar los player_id por nombres.",
      "task": "Muestra el <b>nombre</b> y la <b>hour</b> de todos los que usaron el cofre el <b>día 9</b> a las <b>20:00 o más tarde</b>. Son tus sospechosos.",
      "hint": "chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20"
     },
     "de": {
      "idea": "Hinweis 2: nächtliche Besucher",
      "lesson": "Am Abend von Tag 9 war die Truhe noch in Ordnung. Wer kam in der Nacht? Mit einem JOIN machst du aus player_ids Namen.",
      "task": "Zeig <b>Name</b> und <b>hour</b> aller, die die Truhe an <b>Tag 9</b> um <b>20 Uhr oder später</b> benutzt haben. Das sind deine Verdächtigen.",
      "hint": "chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20"
     }
    }
   },
   {
    "answer": "SELECT p.name, t.day, t.amount * i.value AS emeralds FROM trades t JOIN players p ON t.player_id = p.id JOIN items i ON t.item = i.name WHERE t.item = 'diamond'",
    "example": "SELECT m.name, m.health * i.value\nFROM mobs m JOIN items i ON m.loot = i.name",
    "text": {
     "en": {
      "idea": "Clue 3: follow the money",
      "lesson": "A thief wants to sell the loot. You can calculate across joined tables: <code>t.amount * i.value</code>.",
      "task": "Show every <b>diamond trade</b>: the player's <b>name</b>, the <b>day</b>, and how many <b>emeralds</b> it was worth (amount × value).",
      "hint": "Join trades t with players p and with items i ON t.item = i.name; SELECT p.name, t.day, t.amount * i.value"
     },
     "es": {
      "idea": "Pista 3: sigue el dinero",
      "lesson": "Un ladrón quiere vender el botín. Puedes calcular entre tablas unidas: <code>t.amount * i.value</code>.",
      "task": "Muestra cada <b>venta de diamantes</b>: el <b>nombre</b> del jugador, el <b>day</b> y cuántas <b>esmeraldas</b> valió (amount × value).",
      "hint": "Une trades t con players p y con items i ON t.item = i.name; SELECT p.name, t.day, t.amount * i.value"
     },
     "de": {
      "idea": "Hinweis 3: folge dem Geld",
      "lesson": "Ein Dieb will die Beute verkaufen. Du kannst über verbundene Tabellen rechnen: <code>t.amount * i.value</code>.",
      "task": "Zeig jeden <b>Diamantenverkauf</b>: den <b>Namen</b> des Spielers, den <b>day</b> und wie viele <b>Smaragde</b> er wert war (amount × value).",
      "hint": "Verbinde trades t mit players p und mit items i ON t.item = i.name; SELECT p.name, t.day, t.amount * i.value"
     }
    },
    "freeNames": true
   },
   {
    "answer": "SELECT p.name, SUM(t.amount) FROM trades t JOIN players p ON t.player_id = p.id WHERE t.item = 'diamond' AND t.day > 9 GROUP BY p.name",
    "example": null,
    "text": {
     "en": {
      "idea": "Clue 4: who sold how much?",
      "lesson": "Luna took 2 diamonds and wrote it in the log — that's allowed. But 10 diamonds are still missing…",
      "task": "After day 9 (<b>day &gt; 9</b>), how many diamonds did each player sell <b>in total</b>? Show the <b>name</b> and the total.",
      "hint": "WHERE t.item = 'diamond' AND t.day > 9, GROUP BY p.name, SUM(t.amount)"
     },
     "es": {
      "idea": "Pista 4: ¿quién vendió cuánto?",
      "lesson": "Luna sacó 2 diamantes y lo apuntó en el registro — eso está permitido. Pero aún faltan 10…",
      "task": "Después del día 9 (<b>day &gt; 9</b>), ¿cuántos diamantes vendió cada jugador <b>en total</b>? Muestra el <b>nombre</b> y el total.",
      "hint": "WHERE t.item = 'diamond' AND t.day > 9, GROUP BY p.name, SUM(t.amount)"
     },
     "de": {
      "idea": "Hinweis 4: Wer hat wie viel verkauft?",
      "lesson": "Luna hat 2 Diamanten genommen und es ins Log geschrieben — das ist erlaubt. Aber 10 fehlen immer noch…",
      "task": "Wie viele Diamanten hat jeder Spieler nach Tag 9 (<b>day &gt; 9</b>) <b>insgesamt</b> verkauft? Zeig den <b>Namen</b> und die Summe.",
      "hint": "WHERE t.item = 'diamond' AND t.day > 9, GROUP BY p.name, SUM(t.amount)"
     }
    }
   },
   {
    "answer": "SELECT name FROM players WHERE id IN (SELECT player_id FROM chest_log WHERE day = 9 AND hour >= 20) AND id IN (SELECT player_id FROM trades WHERE item = 'diamond' AND day > 9)",
    "example": "SELECT name FROM players\nWHERE id IN (SELECT player_id FROM hunts WHERE biome = 'caves')",
    "text": {
     "en": {
      "idea": "Subquery with IN",
      "lesson": "A query can live <b>inside</b> another one. <code>WHERE id IN (SELECT player_id FROM …)</code> first runs the inner query, then keeps only the ids that are in its result.",
      "task": "Name the thief: the player who used the chest on <b>night 9</b> (hour ≥ 20) <b>and</b> sold diamonds <b>after day 9</b>. Use two <code>IN (SELECT …)</code>.",
      "hint": "SELECT name FROM players WHERE id IN (… night visitors …) AND id IN (… diamond sellers after day 9 …)"
     },
     "es": {
      "idea": "Subconsulta con IN",
      "lesson": "Una consulta puede vivir <b>dentro</b> de otra. <code>WHERE id IN (SELECT player_id FROM …)</code> primero ejecuta la consulta de dentro y luego se queda solo con los ids de su resultado.",
      "task": "Nombra al ladrón: el jugador que usó el cofre la <b>noche del 9</b> (hour ≥ 20) <b>y</b> vendió diamantes <b>después del día 9</b>. Usa dos <code>IN (SELECT …)</code>.",
      "hint": "SELECT name FROM players WHERE id IN (… visitas nocturnas …) AND id IN (… vendedores de diamantes después del día 9 …)"
     },
     "de": {
      "idea": "Unterabfrage mit IN",
      "lesson": "Eine Abfrage kann <b>in</b> einer anderen stecken. <code>WHERE id IN (SELECT player_id FROM …)</code> führt zuerst die innere Abfrage aus und behält dann nur die ids aus ihrem Ergebnis.",
      "task": "Nenn den Dieb: den Spieler, der in <b>Nacht 9</b> (hour ≥ 20) an der Truhe war <b>und</b> <b>nach Tag 9</b> Diamanten verkauft hat. Nimm zwei <code>IN (SELECT …)</code>.",
      "hint": "SELECT name FROM players WHERE id IN (… nächtliche Besucher …) AND id IN (… Diamantenverkäufer nach Tag 9 …)"
     }
    }
   },
   {
    "answer": "WITH suspects AS (SELECT player_id FROM chest_log WHERE day = 9 AND hour >= 20), sold AS (SELECT player_id, SUM(amount) AS diamonds FROM trades WHERE item = 'diamond' AND day > 9 GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN suspects su ON su.player_id = p.id JOIN sold s ON s.player_id = p.id",
    "example": "WITH big AS (SELECT * FROM mobs WHERE health > 20)\nSELECT name FROM big",
    "text": {
     "en": {
      "idea": "WITH",
      "lesson": "<code>WITH name AS (SELECT …)</code> gives a query a name, so you can use it like a table further down. It makes long detective work readable.",
      "task": "Write the <b>case report</b>: using <code>WITH</code>, make a list of night visitors and a list of diamonds sold after day 9, then show the thief's <b>name</b> and <b>how many diamonds</b> they sold.",
      "hint": "WITH suspects AS (…), sold AS (SELECT player_id, SUM(amount) AS diamonds … GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN …"
     },
     "es": {
      "idea": "WITH",
      "lesson": "<code>WITH nombre AS (SELECT …)</code> le pone nombre a una consulta, para usarla más abajo como si fuera una tabla. Hace legible el trabajo de detective largo.",
      "task": "Escribe el <b>informe del caso</b>: con <code>WITH</code>, haz una lista de visitas nocturnas y otra de diamantes vendidos después del día 9, y muestra el <b>nombre</b> del ladrón y <b>cuántos diamantes</b> vendió.",
      "hint": "WITH suspects AS (…), sold AS (SELECT player_id, SUM(amount) AS diamonds … GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN …"
     },
     "de": {
      "idea": "WITH",
      "lesson": "<code>WITH name AS (SELECT …)</code> gibt einer Abfrage einen Namen, damit du sie weiter unten wie eine Tabelle benutzen kannst. So bleibt lange Detektivarbeit lesbar.",
      "task": "Schreib den <b>Fallbericht</b>: Mach mit <code>WITH</code> eine Liste der nächtlichen Besucher und eine der nach Tag 9 verkauften Diamanten, und zeig dann den <b>Namen</b> des Diebs und <b>wie viele Diamanten</b> er verkauft hat.",
      "hint": "WITH suspects AS (…), sold AS (SELECT player_id, SUM(amount) AS diamonds … GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN …"
     }
    },
    "freeNames": true
   }
  ],
  "boss": true
 },
 {
  "id": "sq8",
  "tables": [
   "mobs",
   "hunts",
   "players"
  ],
  "text": {
   "en": {
    "title": "Bonus: Leaderboards",
    "story": "Bonus chapter ⭐ — tools that real analysts love. <b>Window functions</b> calculate across rows <i>without</i> squashing them into groups: ranks, running totals, the best in each group."
   },
   "es": {
    "title": "Extra: clasificaciones",
    "story": "Capítulo extra ⭐ — herramientas que encantan a los analistas. Las <b>funciones de ventana</b> calculan entre filas <i>sin</i> juntarlas en grupos: puestos, totales acumulados, el mejor de cada grupo."
   },
   "de": {
    "title": "Bonus: Bestenlisten",
    "story": "Bonuskapitel ⭐ — Werkzeuge, die echte Analysten lieben. <b>Fensterfunktionen</b> rechnen über Zeilen hinweg, <i>ohne</i> sie zu Gruppen zusammenzuquetschen: Ränge, laufende Summen, die Besten jeder Gruppe."
   }
  },
  "quests": [
   {
    "answer": "SELECT name, health, RANK() OVER (ORDER BY health DESC) FROM mobs",
    "example": "SELECT name, damage,\n  RANK() OVER (ORDER BY damage DESC) AS place\nFROM mobs",
    "text": {
     "en": {
      "idea": "RANK() OVER",
      "lesson": "<code>RANK() OVER (ORDER BY … DESC)</code> gives every row its place: 1, 2, 3… Rows that tie get the same place.",
      "task": "Rank all mobs by <b>health</b>, highest first. Show <b>name</b>, <b>health</b> and the <b>rank</b>.",
      "hint": "RANK() OVER (ORDER BY health DESC)"
     },
     "es": {
      "idea": "RANK() OVER",
      "lesson": "<code>RANK() OVER (ORDER BY … DESC)</code> le da a cada fila su puesto: 1, 2, 3… Las filas empatadas reciben el mismo puesto.",
      "task": "Clasifica todas las criaturas por <b>health</b>, de mayor a menor. Muestra <b>name</b>, <b>health</b> y el <b>puesto</b>.",
      "hint": "RANK() OVER (ORDER BY health DESC)"
     },
     "de": {
      "idea": "RANK() OVER",
      "lesson": "<code>RANK() OVER (ORDER BY … DESC)</code> gibt jeder Zeile ihren Platz: 1, 2, 3… Gleichstände bekommen denselben Platz.",
      "task": "Ordne alle Mobs nach <b>health</b>, das höchste zuerst. Zeig <b>name</b>, <b>health</b> und den <b>Rang</b>.",
      "hint": "RANK() OVER (ORDER BY health DESC)"
     }
    },
    "freeNames": true
   },
   {
    "answer": "SELECT name, type, damage, RANK() OVER (PARTITION BY type ORDER BY damage DESC) FROM mobs",
    "example": "SELECT name, home, health,\n  RANK() OVER (PARTITION BY home ORDER BY health DESC)\nFROM mobs",
    "text": {
     "en": {
      "idea": "PARTITION BY",
      "lesson": "<code>PARTITION BY type</code> restarts the ranking for every type — a \"rank inside each group\".",
      "task": "Rank the mobs by <b>damage</b> <b>inside each type</b>. Show <b>name</b>, <b>type</b>, <b>damage</b> and the rank.",
      "hint": "RANK() OVER (PARTITION BY type ORDER BY damage DESC)"
     },
     "es": {
      "idea": "PARTITION BY",
      "lesson": "<code>PARTITION BY type</code> reinicia la clasificación para cada tipo — un \"puesto dentro de cada grupo\".",
      "task": "Clasifica las criaturas por <b>damage</b> <b>dentro de cada type</b>. Muestra <b>name</b>, <b>type</b>, <b>damage</b> y el puesto.",
      "hint": "RANK() OVER (PARTITION BY type ORDER BY damage DESC)"
     },
     "de": {
      "idea": "PARTITION BY",
      "lesson": "<code>PARTITION BY type</code> fängt die Rangliste für jeden Typ neu an — ein \"Rang innerhalb jeder Gruppe\".",
      "task": "Ordne die Mobs nach <b>damage</b> <b>innerhalb jedes type</b>. Zeig <b>name</b>, <b>type</b>, <b>damage</b> und den Rang.",
      "hint": "RANK() OVER (PARTITION BY type ORDER BY damage DESC)"
     }
    },
    "freeNames": true
   },
   {
    "answer": "WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d",
    "example": "WITH d AS (SELECT day, COUNT(*) AS n FROM hunts GROUP BY day)\nSELECT day, n, SUM(n) OVER (ORDER BY day) FROM d",
    "text": {
     "en": {
      "idea": "Running total",
      "lesson": "<code>SUM(x) OVER (ORDER BY day)</code> adds up everything <b>so far</b> — a running total. Tip: first make daily totals with <code>WITH</code>, then run the window over them.",
      "task": "Show each <b>day</b>, the <b>XP earned that day</b>, and the <b>running total</b> of XP up to that day.",
      "hint": "WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d"
     },
     "es": {
      "idea": "Total acumulado",
      "lesson": "<code>SUM(x) OVER (ORDER BY day)</code> suma todo lo que va <b>hasta ahora</b> — un total acumulado. Consejo: primero calcula los totales por día con <code>WITH</code> y luego aplica la ventana.",
      "task": "Muestra cada <b>day</b>, la <b>XP ganada ese día</b> y el <b>total acumulado</b> de XP hasta ese día.",
      "hint": "WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d"
     },
     "de": {
      "idea": "Laufende Summe",
      "lesson": "<code>SUM(x) OVER (ORDER BY day)</code> zählt alles <b>bis jetzt</b> zusammen — eine laufende Summe. Tipp: Rechne zuerst mit <code>WITH</code> die Tagessummen aus und lass dann das Fenster darüber laufen.",
      "task": "Zeig jeden <b>day</b>, die <b>XP dieses Tages</b> und die <b>laufende Summe</b> der XP bis zu diesem Tag.",
      "hint": "WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d"
     }
    },
    "freeNames": true
   },
   {
    "answer": "WITH t AS (SELECT p.name, SUM(h.xp) AS total FROM hunts h JOIN players p ON h.player_id = p.id GROUP BY p.name) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t",
    "example": null,
    "text": {
     "en": {
      "idea": "Final leaderboard",
      "lesson": "Put it all together: JOIN, GROUP BY, WITH and RANK — this is exactly how real game leaderboards are built.",
      "task": "Build the final leaderboard: each <b>player name</b>, their <b>total XP</b>, and their <b>rank</b>.",
      "hint": "WITH t AS (… player name + SUM(xp) …) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t"
     },
     "es": {
      "idea": "Clasificación final",
      "lesson": "Júntalo todo: JOIN, GROUP BY, WITH y RANK — así se construyen las clasificaciones de los juegos de verdad.",
      "task": "Construye la clasificación final: el <b>nombre de cada jugador</b>, su <b>XP total</b> y su <b>puesto</b>.",
      "hint": "WITH t AS (… nombre + SUM(xp) …) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t"
     },
     "de": {
      "idea": "Die finale Bestenliste",
      "lesson": "Alles zusammen: JOIN, GROUP BY, WITH und RANK — genau so werden echte Spiel-Bestenlisten gebaut.",
      "task": "Bau die finale Bestenliste: jeder <b>Spielername</b>, seine <b>gesamte XP</b> und sein <b>Rang</b>.",
      "hint": "WITH t AS (… Spielername + SUM(xp) …) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t"
     }
    },
    "freeNames": true
   }
  ],
  "bonus": true
 }
];
})();
