"""Generate js/levels-sql.js: 8 chapters, one new idea per quest, EN/ES/DE."""
import json, sys
sys.path.insert(0, __import__('os').path.dirname(__file__))
from answers import A

# Each quest: key, options, example, and per language [idea, lesson, task, hint].
CH = []

def chapter(cid, tables, title, story, quests, **kw):
    CH.append(dict(id=cid, tables=tables, text={l: {'title': title[l], 'story': story[l]} for l in title}, quests=quests, **kw))

def q(key, ex, en, es, de, **opts):
    d = dict(answer=A[key], example=ex, text={'en': dict(zip(['idea', 'lesson', 'task', 'hint'], en)),
                                              'es': dict(zip(['idea', 'lesson', 'task', 'hint'], es)),
                                              'de': dict(zip(['idea', 'lesson', 'task', 'hint'], de))})
    d.update(opts)
    return d

# ---------------------------------------------------------------- 1
chapter('sq1', ['mobs'],
 {'en': 'Open the Mobdex', 'es': 'Abre el Mobdex', 'de': 'Öffne den Mobdex'},
 {'en': 'You found an ancient Mobdex — a database with info on every mob. It only answers questions written in <b>SQL</b>, the language real data analysts use every day.',
  'es': 'Has encontrado un Mobdex antiguo — una base de datos con información de cada criatura. Solo responde a preguntas escritas en <b>SQL</b>, el lenguaje que usan los analistas de datos cada día.',
  'de': 'Du hast einen uralten Mobdex gefunden — eine Datenbank mit Infos über jeden Mob. Er beantwortet nur Fragen in <b>SQL</b>, der Sprache, die echte Datenanalysten jeden Tag benutzen.'},
 [
 q('1.1', 'SELECT * FROM mobs',
   ['SELECT * FROM', 'A <b>database</b> keeps data in <b>tables</b>, like a spreadsheet. <code>SELECT</code> says what you want to see, <code>FROM</code> says which table. <code>*</code> means "every column".', 'Show <b>everything</b> in the <code>mobs</code> table. The code is already there — just press ▶ Run!', 'Just press Run 🙂'],
   ['SELECT * FROM', 'Una <b>base de datos</b> guarda datos en <b>tablas</b>, como una hoja de cálculo. <code>SELECT</code> dice qué quieres ver, <code>FROM</code> de qué tabla. <code>*</code> significa "todas las columnas".', 'Muestra <b>todo</b> lo que hay en la tabla <code>mobs</code>. El código ya está escrito — ¡solo pulsa ▶ Ejecutar!', 'Solo pulsa Ejecutar 🙂'],
   ['SELECT * FROM', 'Eine <b>Datenbank</b> speichert Daten in <b>Tabellen</b>, wie eine Tabellenkalkulation. <code>SELECT</code> sagt, was du sehen willst, <code>FROM</code> aus welcher Tabelle. <code>*</code> heißt "alle Spalten".', 'Zeig <b>alles</b> aus der Tabelle <code>mobs</code>. Der Code steht schon da — drück einfach ▶ Start!', 'Drück einfach Start 🙂'],
   starter='SELECT * FROM mobs', unlock={'mobs': [1, 2, 14]}),
 q('1.2', 'SELECT name, type FROM mobs',
   ['Pick columns', 'Instead of <code>*</code>, write the column names you want, separated by <b>commas</b>. The tables on the right show every column name.', 'Show only the <b>name</b> and <b>health</b> of every mob.', 'Replace * with the two column names, with a comma between them.'],
   ['Elegir columnas', 'En lugar de <code>*</code>, escribe los nombres de las columnas que quieres, separados por <b>comas</b>. Las tablas de la derecha muestran todos los nombres.', 'Muestra solo el <b>name</b> y la <b>health</b> de cada criatura.', 'Cambia el * por los dos nombres de columna, con una coma entre ellos.'],
   ['Spalten auswählen', 'Statt <code>*</code> schreibst du die Spaltennamen, die du willst, getrennt durch <b>Kommas</b>. Rechts siehst du alle Spaltennamen.', 'Zeig nur <b>name</b> und <b>health</b> von jedem Mob.', 'Ersetze * durch die zwei Spaltennamen, mit einem Komma dazwischen.'],
   unlock={'mobs': [3, 15]}),
 q('1.3', 'SELECT name, damage FROM mobs ORDER BY damage',
   ['ORDER BY', '<code>ORDER BY column</code> sorts the rows, smallest first. Add <code>DESC</code> to put the biggest first. It goes at the end of the query.', 'Show <b>name</b> and <b>health</b>, sorted from the <b>most</b> health to the least.', 'Add ORDER BY health DESC at the end.'],
   ['ORDER BY', '<code>ORDER BY columna</code> ordena las filas, de menor a mayor. Añade <code>DESC</code> para poner primero el mayor. Va al final de la consulta.', 'Muestra <b>name</b> y <b>health</b>, ordenados de <b>más</b> vida a menos.', 'Añade ORDER BY health DESC al final.'],
   ['ORDER BY', '<code>ORDER BY spalte</code> sortiert die Zeilen, das Kleinste zuerst. Mit <code>DESC</code> kommt das Größte zuerst. Es steht am Ende der Abfrage.', 'Zeig <b>name</b> und <b>health</b>, sortiert vom <b>meisten</b> Leben zum wenigsten.', 'Schreib ORDER BY health DESC ans Ende.'],
   orderCol=1, unlock={'mobs': [4, 17]}),
 q('1.4', 'SELECT name, damage FROM mobs ORDER BY damage DESC LIMIT 5',
   ['LIMIT', '<code>LIMIT 5</code> keeps only the first 5 rows. Together with ORDER BY it makes a "top 5".', 'Show <b>name</b> and <b>health</b> of the <b>3 toughest</b> mobs.', 'Sort by health, biggest first, then add LIMIT 3.'],
   ['LIMIT', '<code>LIMIT 5</code> se queda solo con las 5 primeras filas. Junto con ORDER BY te da un "top 5".', 'Muestra <b>name</b> y <b>health</b> de las <b>3 más resistentes</b>.', 'Ordena por health de mayor a menor y añade LIMIT 3.'],
   ['LIMIT', '<code>LIMIT 5</code> behält nur die ersten 5 Zeilen. Zusammen mit ORDER BY ergibt das eine "Top 5".', 'Zeig <b>name</b> und <b>health</b> der <b>3 zähesten</b> Mobs.', 'Sortier nach health, das Größte zuerst, dann LIMIT 3.'],
   orderCol=1, unlock={'mobs': [10]}),
 q('1.5', 'SELECT DISTINCT type FROM mobs',
   ['DISTINCT', 'Many mobs share the same home. <code>SELECT DISTINCT</code> removes duplicate rows, so every value shows up only once.', 'Which <b>different homes</b> exist? Show each home only <b>once</b>.', 'Put DISTINCT right after SELECT.'],
   ['DISTINCT', 'Muchas criaturas comparten hogar. <code>SELECT DISTINCT</code> quita las filas repetidas, así cada valor aparece una sola vez.', '¿Qué <b>hogares distintos</b> hay? Muestra cada hogar <b>una sola vez</b>.', 'Pon DISTINCT justo después de SELECT.'],
   ['DISTINCT', 'Viele Mobs haben dasselbe Zuhause. <code>SELECT DISTINCT</code> entfernt doppelte Zeilen, so kommt jeder Wert nur einmal vor.', 'Welche <b>verschiedenen Zuhause</b> gibt es? Zeig jedes nur <b>einmal</b>.', 'Schreib DISTINCT direkt hinter SELECT.'],
   unlock={'mobs': [16, 9]}),
 q('1.6', 'SELECT name, health * 2 AS double_health FROM mobs',
   ['Maths and AS', 'You can calculate inside SELECT with <code>+ - * /</code>. <code>AS</code> gives the new column a name — otherwise it gets an ugly name like <code>damage * 3</code>.', 'A mob hits you <b>3 times</b>. Show each mob\'s <b>name</b> and its total damage, in a column called <code>three_hits</code>.', 'Multiply damage * 3, then name it with AS three_hits.'],
   ['Cálculos y AS', 'Puedes calcular dentro del SELECT con <code>+ - * /</code>. <code>AS</code> le pone nombre a la nueva columna — si no, se llama algo feo como <code>damage * 3</code>.', 'Una criatura te golpea <b>3 veces</b>. Muestra el <b>name</b> de cada una y su daño total, en una columna llamada <code>three_hits</code>.', 'Multiplica damage * 3 y ponle nombre con AS three_hits.'],
   ['Rechnen und AS', 'Im SELECT kannst du mit <code>+ - * /</code> rechnen. <code>AS</code> gibt der neuen Spalte einen Namen — sonst heißt sie hässlich, zum Beispiel <code>damage * 3</code>.', 'Ein Mob trifft dich <b>3-mal</b>. Zeig den <b>name</b> jedes Mobs und seinen Gesamtschaden, in einer Spalte namens <code>three_hits</code>.', 'Rechne damage * 3 und gib ihm mit AS three_hits einen Namen.'],
   requireNames=True, unlock={'mobs': [5, 11]}),
 ])

# ---------------------------------------------------------------- 2
chapter('sq2', ['mobs'],
 {'en': 'Mob Hunter', 'es': 'Cazador de criaturas', 'de': 'Mob-Jäger'},
 {'en': 'Night is coming and you need to know <b>exactly</b> which mobs to watch out for. Time to <b>filter</b> the Mobdex.',
  'es': 'Se acerca la noche y necesitas saber <b>exactamente</b> de qué criaturas cuidarte. Es hora de <b>filtrar</b> el Mobdex.',
  'de': 'Die Nacht kommt, und du musst <b>genau</b> wissen, vor welchen Mobs du aufpassen musst. Zeit, den Mobdex zu <b>filtern</b>.'},
 [
 q('2.1', "SELECT name FROM mobs WHERE type = 'passive'",
   ['WHERE', '<code>WHERE</code> keeps only the rows that match a rule. It comes right after <code>FROM</code>. Text goes in <b>single quotes</b>: <code>\'hostile\'</code>.', 'Show all columns, but only for <b>hostile</b> mobs.', "WHERE type = 'hostile' — don't forget the quotes."],
   ['WHERE', '<code>WHERE</code> se queda solo con las filas que cumplen una regla. Va justo después de <code>FROM</code>. El texto va entre <b>comillas simples</b>: <code>\'hostile\'</code>.', 'Muestra todas las columnas, pero solo de las criaturas <b>hostile</b>.', "WHERE type = 'hostile' — no olvides las comillas."],
   ['WHERE', '<code>WHERE</code> behält nur die Zeilen, die zu einer Regel passen. Es kommt direkt nach <code>FROM</code>. Text kommt in <b>einfache Anführungszeichen</b>: <code>\'hostile\'</code>.', 'Zeig alle Spalten, aber nur für <b>hostile</b> Mobs.', "WHERE type = 'hostile' — vergiss die Anführungszeichen nicht."],
   unlock={'mobs': [6]}),
 q('2.2', 'SELECT name, damage FROM mobs WHERE damage >= 10',
   ['Compare numbers', 'For numbers: <code>&gt;</code> bigger, <code>&lt;</code> smaller, <code>&gt;=</code> bigger or equal, <code>&lt;=</code> smaller or equal, <code>!=</code> not equal. Numbers need <b>no</b> quotes.', 'Show the <b>name</b> of every mob with <b>more than 20</b> health.', '"More than" is &gt;.'],
   ['Comparar números', 'Para números: <code>&gt;</code> mayor, <code>&lt;</code> menor, <code>&gt;=</code> mayor o igual, <code>&lt;=</code> menor o igual, <code>!=</code> distinto. Los números <b>no</b> llevan comillas.', 'Muestra el <b>name</b> de cada criatura con <b>más de 20</b> de vida.', '"Más de" es &gt;.'],
   ['Zahlen vergleichen', 'Für Zahlen: <code>&gt;</code> größer, <code>&lt;</code> kleiner, <code>&gt;=</code> größer oder gleich, <code>&lt;=</code> kleiner oder gleich, <code>!=</code> ungleich. Zahlen brauchen <b>keine</b> Anführungszeichen.', 'Zeig den <b>name</b> jedes Mobs mit <b>mehr als 20</b> Leben.', '"Mehr als" ist &gt;.'],
   unlock={'mobs': [7]}),
 q('2.3', "SELECT name FROM mobs WHERE type = 'passive' AND health > 10",
   ['AND', '<code>AND</code> joins two rules: a row stays only if <b>both</b> are true.', 'Show the <b>name</b> of the <b>hostile</b> mobs that live in the <b>overworld</b>.', "Two rules: type = 'hostile' AND home = 'overworld'"],
   ['AND', '<code>AND</code> une dos reglas: una fila se queda solo si <b>las dos</b> son ciertas.', 'Muestra el <b>name</b> de las criaturas <b>hostile</b> que viven en el <b>overworld</b>.', "Dos reglas: type = 'hostile' AND home = 'overworld'"],
   ['AND', '<code>AND</code> verbindet zwei Regeln: Eine Zeile bleibt nur, wenn <b>beide</b> stimmen.', 'Zeig den <b>name</b> der <b>hostile</b> Mobs, die in der <b>overworld</b> leben.', "Zwei Regeln: type = 'hostile' AND home = 'overworld'"],
   unlock={'mobs': [8]}),
 q('2.4', 'SELECT name FROM mobs WHERE damage > 20 OR health > 50',
   ['OR', '<code>OR</code>: a row stays if <b>at least one</b> of the rules is true.', 'Show <b>name</b> and <b>home</b> of the mobs from the <b>nether</b> or the <b>end</b>.', "home = 'nether' OR home = 'end'"],
   ['OR', '<code>OR</code>: una fila se queda si <b>al menos una</b> de las reglas es cierta.', 'Muestra <b>name</b> y <b>home</b> de las criaturas del <b>nether</b> o del <b>end</b>.', "home = 'nether' OR home = 'end'"],
   ['OR', '<code>OR</code>: Eine Zeile bleibt, wenn <b>mindestens eine</b> der Regeln stimmt.', 'Zeig <b>name</b> und <b>home</b> der Mobs aus dem <b>nether</b> oder dem <b>end</b>.', "home = 'nether' OR home = 'end'"],
   unlock={'mobs': [12]}),
 q('2.5', "SELECT name FROM mobs WHERE home IN ('caves', 'end')",
   ['IN', '<code>IN (…)</code> checks against a whole list — a shortcut for many ORs.', 'Show <b>name</b> and <b>loot</b> of the mobs that drop <b>bone</b>, <b>string</b> or <b>gunpowder</b>.', "loot IN ('bone', 'string', 'gunpowder')"],
   ['IN', '<code>IN (…)</code> compara con una lista entera — un atajo para muchos OR.', 'Muestra <b>name</b> y <b>loot</b> de las criaturas que sueltan <b>bone</b>, <b>string</b> o <b>gunpowder</b>.', "loot IN ('bone', 'string', 'gunpowder')"],
   ['IN', '<code>IN (…)</code> prüft gegen eine ganze Liste — eine Abkürzung für viele ORs.', 'Zeig <b>name</b> und <b>loot</b> der Mobs, die <b>bone</b>, <b>string</b> oder <b>gunpowder</b> fallen lassen.', "loot IN ('bone', 'string', 'gunpowder')"],
   unlock={'mobs': [13]}),
 q('2.6', 'SELECT name, damage FROM mobs WHERE damage BETWEEN 5 AND 10',
   ['BETWEEN', '<code>BETWEEN 5 AND 10</code> keeps values from 5 to 10 — <b>including</b> 5 and 10.', 'Show <b>name</b> and <b>health</b> of the mobs with health <b>between 10 and 20</b>.', 'health BETWEEN 10 AND 20'],
   ['BETWEEN', '<code>BETWEEN 5 AND 10</code> se queda con los valores de 5 a 10 — <b>incluidos</b> el 5 y el 10.', 'Muestra <b>name</b> y <b>health</b> de las criaturas con vida <b>entre 10 y 20</b>.', 'health BETWEEN 10 AND 20'],
   ['BETWEEN', '<code>BETWEEN 5 AND 10</code> behält Werte von 5 bis 10 — <b>mit</b> 5 und 10.', 'Zeig <b>name</b> und <b>health</b> der Mobs mit Leben <b>zwischen 10 und 20</b>.', 'health BETWEEN 10 AND 20'],
   unlock={'mobs': [18]}),
 q('2.7', "SELECT name FROM mobs WHERE name LIKE 'S%'",
   ['LIKE', '<code>LIKE</code> searches text with a pattern. <code>%</code> means "any letters (or none)": <code>\'S%\'</code> finds names starting with S, <code>\'%ie%\'</code> finds "ie" anywhere.', 'Show the <b>name</b> of every mob with <b>skeleton</b> anywhere in its name.', "Put % on both sides: '%skeleton%'"],
   ['LIKE', '<code>LIKE</code> busca texto con un patrón. <code>%</code> significa "cualquier letra (o ninguna)": <code>\'S%\'</code> encuentra nombres que empiezan por S, <code>\'%ie%\'</code> encuentra "ie" en cualquier parte.', 'Muestra el <b>name</b> de cada criatura con <b>skeleton</b> en cualquier parte del nombre.', "Pon % a los dos lados: '%skeleton%'"],
   ['LIKE', '<code>LIKE</code> sucht Text mit einem Muster. <code>%</code> heißt "beliebige Buchstaben (oder keine)": <code>\'S%\'</code> findet Namen mit S am Anfang, <code>\'%ie%\'</code> findet "ie" irgendwo.', 'Zeig den <b>name</b> jedes Mobs, der irgendwo <b>skeleton</b> im Namen hat.', "Setz % auf beide Seiten: '%skeleton%'"],
   unlock={'mobs': [19]}),
 q('2.8', 'SELECT name, loot FROM mobs WHERE loot IS NOT NULL',
   ['IS NULL', '<code>NULL</code> means "empty — no value at all". Some mobs drop nothing, so their loot is NULL. <code>= NULL</code> never works; write <code>IS NULL</code> (or <code>IS NOT NULL</code>).', 'Show the <b>name</b> of the mobs that drop <b>no loot</b>.', 'loot IS NULL'],
   ['IS NULL', '<code>NULL</code> significa "vacío — ningún valor". Algunas criaturas no sueltan nada, así que su loot es NULL. <code>= NULL</code> nunca funciona; escribe <code>IS NULL</code> (o <code>IS NOT NULL</code>).', 'Muestra el <b>name</b> de las criaturas que <b>no sueltan nada</b>.', 'loot IS NULL'],
   ['IS NULL', '<code>NULL</code> heißt "leer — gar kein Wert". Manche Mobs lassen nichts fallen, ihr loot ist NULL. <code>= NULL</code> klappt nie; schreib <code>IS NULL</code> (oder <code>IS NOT NULL</code>).', 'Zeig den <b>name</b> der Mobs, die <b>keine Beute</b> fallen lassen.', 'loot IS NULL'],
   unlock={'mobs': [20]}),
 ])

# ---------------------------------------------------------------- 3
chapter('sq3', ['hunts'],
 {'en': 'The Hunt Log', 'es': 'El registro de cacerías', 'de': 'Das Jagdbuch'},
 {'en': 'The village keeps a <b>log of every hunt</b>: the table <code>hunts</code>. One row = one hunt: the day, who (<code>player_id</code>), which mob (<code>mob_id</code>), where, how much loot and XP. Time to <b>add things up</b>.',
  'es': 'La aldea guarda un <b>registro de cada cacería</b>: la tabla <code>hunts</code>. Una fila = una cacería: el día, quién (<code>player_id</code>), qué criatura (<code>mob_id</code>), dónde, cuánto botín y XP. Es hora de <b>sumar</b>.',
  'de': 'Das Dorf führt ein <b>Buch über jede Jagd</b>: die Tabelle <code>hunts</code>. Eine Zeile = eine Jagd: der Tag, wer (<code>player_id</code>), welcher Mob (<code>mob_id</code>), wo, wie viel Beute und XP. Zeit <b>zusammenzurechnen</b>.'},
 [
 q('3.1', "SELECT * FROM hunts WHERE biome = 'nether'",
   ['A log table', 'Real companies store what happens as a <b>log</b>: one row per event. <code>player_id</code> and <code>mob_id</code> are numbers that point to rows in other tables — you\'ll connect them later.', 'Show all hunts from <b>day 1</b>.', 'WHERE day = 1'],
   ['Una tabla de registro', 'Las empresas guardan lo que pasa como un <b>registro</b>: una fila por cada suceso. <code>player_id</code> y <code>mob_id</code> son números que apuntan a filas de otras tablas — más tarde las conectarás.', 'Muestra todas las cacerías del <b>día 1</b>.', 'WHERE day = 1'],
   ['Eine Logtabelle', 'Echte Firmen speichern, was passiert, als <b>Log</b>: eine Zeile pro Ereignis. <code>player_id</code> und <code>mob_id</code> sind Zahlen, die auf Zeilen in anderen Tabellen zeigen — die verbindest du später.', 'Zeig alle Jagden von <b>Tag 1</b>.', 'WHERE day = 1'],
   unlock={'items': [1]}),
 q('3.2', 'SELECT COUNT(*) FROM mobs',
   ['COUNT(*)', '<code>COUNT(*)</code> counts the rows instead of showing them. You get one number.', '<b>How many hunts</b> are in the log?', 'SELECT COUNT(*) FROM …'],
   ['COUNT(*)', '<code>COUNT(*)</code> cuenta las filas en vez de mostrarlas. Obtienes un solo número.', '¿<b>Cuántas cacerías</b> hay en el registro?', 'SELECT COUNT(*) FROM …'],
   ['COUNT(*)', '<code>COUNT(*)</code> zählt die Zeilen, statt sie zu zeigen. Du bekommst eine einzige Zahl.', '<b>Wie viele Jagden</b> stehen im Buch?', 'SELECT COUNT(*) FROM …'],
   unlock={'items': [2]}),
 q('3.3', 'SELECT SUM(loot_count) FROM hunts',
   ['SUM', '<code>SUM(column)</code> adds up all the numbers in a column.', 'How much <b>XP</b> did everybody earn <b>in total</b>?', 'SUM(xp)'],
   ['SUM', '<code>SUM(columna)</code> suma todos los números de una columna.', '¿Cuánta <b>XP</b> ganaron todos <b>en total</b>?', 'SUM(xp)'],
   ['SUM', '<code>SUM(spalte)</code> zählt alle Zahlen einer Spalte zusammen.', 'Wie viel <b>XP</b> haben alle <b>zusammen</b> verdient?', 'SUM(xp)'],
   unlock={'items': [3]}),
 q('3.4', 'SELECT ROUND(AVG(health), 1) FROM mobs',
   ['AVG and ROUND', '<code>AVG(column)</code> is the average. Averages often have long decimals, so <code>ROUND(x, 1)</code> rounds to 1 decimal place.', 'What is the <b>average XP</b> per hunt, <b>rounded to 1 decimal</b>?', 'Put AVG(xp) inside ROUND( … , 1).'],
   ['AVG y ROUND', '<code>AVG(columna)</code> es la media. Las medias suelen tener muchos decimales, así que <code>ROUND(x, 1)</code> redondea a 1 decimal.', '¿Cuál es la <b>XP media</b> por cacería, <b>redondeada a 1 decimal</b>?', 'Mete AVG(xp) dentro de ROUND( … , 1).'],
   ['AVG und ROUND', '<code>AVG(spalte)</code> ist der Durchschnitt. Der hat oft viele Nachkommastellen, deshalb rundet <code>ROUND(x, 1)</code> auf 1 Stelle.', 'Wie viel <b>XP</b> bringt eine Jagd <b>im Durchschnitt</b>, <b>auf 1 Stelle gerundet</b>?', 'Pack AVG(xp) in ROUND( … , 1).'],
   unlock={'items': [4]}),
 q('3.5', 'SELECT MIN(health), MAX(health) FROM mobs',
   ['MIN and MAX', '<code>MIN</code> finds the smallest value, <code>MAX</code> the biggest. You can put several of them in one SELECT.', 'Show the <b>biggest</b> and the <b>smallest</b> XP from a single hunt.', 'SELECT MAX(xp), MIN(xp) …'],
   ['MIN y MAX', '<code>MIN</code> encuentra el valor más pequeño, <code>MAX</code> el más grande. Puedes poner varios en un mismo SELECT.', 'Muestra la XP <b>más grande</b> y la <b>más pequeña</b> de una sola cacería.', 'SELECT MAX(xp), MIN(xp) …'],
   ['MIN und MAX', '<code>MIN</code> findet den kleinsten Wert, <code>MAX</code> den größten. Du kannst mehrere in ein SELECT schreiben.', 'Zeig die <b>größte</b> und die <b>kleinste</b> XP einer einzelnen Jagd.', 'SELECT MAX(xp), MIN(xp) …'],
   unlock={'items': [5]}),
 q('3.6', 'SELECT COUNT(DISTINCT home) FROM mobs',
   ['COUNT(DISTINCT)', '<code>COUNT(DISTINCT column)</code> counts how many <b>different</b> values there are.', '<b>How many different players</b> went hunting?', 'Count the different player_id values.'],
   ['COUNT(DISTINCT)', '<code>COUNT(DISTINCT columna)</code> cuenta cuántos valores <b>distintos</b> hay.', '¿<b>Cuántos jugadores distintos</b> salieron a cazar?', 'Cuenta los valores distintos de player_id.'],
   ['COUNT(DISTINCT)', '<code>COUNT(DISTINCT spalte)</code> zählt, wie viele <b>verschiedene</b> Werte es gibt.', '<b>Wie viele verschiedene Spieler</b> waren jagen?', 'Zähl die verschiedenen player_id-Werte.'],
   unlock={'items': [6]}),
 q('3.7', 'SELECT COUNT(*) FROM hunts WHERE day = 3',
   ['Totals with a rule', 'WHERE works together with SUM and COUNT: first the rows are filtered, then they\'re added up.', 'How much <b>XP</b> was earned in the <b>nether</b>?', "SUM(xp) … WHERE biome = 'nether'"],
   ['Totales con una regla', 'WHERE funciona junto con SUM y COUNT: primero se filtran las filas, luego se suman.', '¿Cuánta <b>XP</b> se ganó en el <b>nether</b>?', "SUM(xp) … WHERE biome = 'nether'"],
   ['Summen mit Regel', 'WHERE klappt zusammen mit SUM und COUNT: Erst werden die Zeilen gefiltert, dann zusammengezählt.', 'Wie viel <b>XP</b> wurde im <b>nether</b> verdient?', "SUM(xp) … WHERE biome = 'nether'"],
   unlock={'items': [7]}),
 ])

# ---------------------------------------------------------------- 4
chapter('sq4', ['hunts'],
 {'en': 'Village Report', 'es': 'Informe de la aldea', 'de': 'Dorfbericht'},
 {'en': 'The village elder wants a report — not one big total, but <b>one line per player, per day, per biome</b>. That\'s what <code>GROUP BY</code> is for: the most important tool in data analysis.',
  'es': 'El anciano de la aldea quiere un informe — no un solo total, sino <b>una línea por jugador, por día, por bioma</b>. Para eso sirve <code>GROUP BY</code>: la herramienta más importante del análisis de datos.',
  'de': 'Der Dorfälteste will einen Bericht — nicht eine große Summe, sondern <b>eine Zeile pro Spieler, pro Tag, pro Biom</b>. Dafür gibt es <code>GROUP BY</code>: das wichtigste Werkzeug der Datenanalyse.'},
 [
 q('4.1', 'SELECT type, COUNT(*) FROM mobs GROUP BY type',
   ['GROUP BY', '<code>GROUP BY biome</code> puts rows with the same biome together and gives you <b>one row per group</b>. COUNT, SUM and AVG then work <b>inside each group</b>. Put the group column in the SELECT too, so you can see which group is which.', 'Show each <b>biome</b> and <b>how many hunts</b> happened there.', 'SELECT biome, COUNT(*) … GROUP BY biome'],
   ['GROUP BY', '<code>GROUP BY biome</code> junta las filas con el mismo bioma y te da <b>una fila por grupo</b>. COUNT, SUM y AVG trabajan entonces <b>dentro de cada grupo</b>. Pon también la columna del grupo en el SELECT, para ver qué grupo es cuál.', 'Muestra cada <b>biome</b> y <b>cuántas cacerías</b> hubo allí.', 'SELECT biome, COUNT(*) … GROUP BY biome'],
   ['GROUP BY', '<code>GROUP BY biome</code> packt Zeilen mit demselben Biom zusammen und gibt dir <b>eine Zeile pro Gruppe</b>. COUNT, SUM und AVG rechnen dann <b>in jeder Gruppe</b>. Schreib die Gruppenspalte auch ins SELECT, damit du siehst, welche Gruppe welche ist.', 'Zeig jedes <b>biome</b> und <b>wie viele Jagden</b> dort waren.', 'SELECT biome, COUNT(*) … GROUP BY biome'],
   unlock={'items': [8]}),
 q('4.2', 'SELECT home, SUM(health) AS total FROM mobs GROUP BY home ORDER BY total DESC',
   ['Sort by a total', 'Give the total a name with <code>AS</code>, then you can sort by that name: <code>ORDER BY total DESC</code>.', 'Show each <b>player_id</b> and their <b>total XP</b>, best player first.', 'SUM(xp) AS total, GROUP BY player_id, then ORDER BY total DESC.'],
   ['Ordenar por un total', 'Ponle nombre al total con <code>AS</code> y luego podrás ordenar por ese nombre: <code>ORDER BY total DESC</code>.', 'Muestra cada <b>player_id</b> y su <b>XP total</b>, el mejor primero.', 'SUM(xp) AS total, GROUP BY player_id y luego ORDER BY total DESC.'],
   ['Nach einer Summe sortieren', 'Gib der Summe mit <code>AS</code> einen Namen, dann kannst du danach sortieren: <code>ORDER BY total DESC</code>.', 'Zeig jede <b>player_id</b> und ihre <b>gesamte XP</b>, der beste Spieler zuerst.', 'SUM(xp) AS total, GROUP BY player_id, dann ORDER BY total DESC.'],
   orderCol=1, unlock={'items': [9]}),
 q('4.3', 'SELECT type, home, COUNT(*) FROM mobs GROUP BY type, home',
   ['Group by 2 columns', 'You can group by several columns: <code>GROUP BY a, b</code> makes one row for every <b>combination</b> of a and b.', 'How many hunts did each <b>player_id</b> have in each <b>biome</b>?', 'GROUP BY player_id, biome'],
   ['Agrupar por 2 columnas', 'Puedes agrupar por varias columnas: <code>GROUP BY a, b</code> crea una fila por cada <b>combinación</b> de a y b.', '¿Cuántas cacerías tuvo cada <b>player_id</b> en cada <b>biome</b>?', 'GROUP BY player_id, biome'],
   ['Nach 2 Spalten gruppieren', 'Du kannst nach mehreren Spalten gruppieren: <code>GROUP BY a, b</code> macht eine Zeile für jede <b>Kombination</b> aus a und b.', 'Wie viele Jagden hatte jede <b>player_id</b> in jedem <b>biome</b>?', 'GROUP BY player_id, biome'],
   unlock={'items': [10]}),
 q('4.4', 'SELECT home, COUNT(*) FROM mobs GROUP BY home HAVING COUNT(*) > 2',
   ['HAVING', '<code>WHERE</code> filters single rows <b>before</b> grouping. To filter whole <b>groups</b> (for example by their COUNT), use <code>HAVING</code> after GROUP BY.', 'Which <b>days</b> had <b>more than 6 hunts</b>? Show the day and its count.', 'GROUP BY day HAVING COUNT(*) > 6'],
   ['HAVING', '<code>WHERE</code> filtra filas sueltas <b>antes</b> de agrupar. Para filtrar <b>grupos</b> enteros (por ejemplo por su COUNT), usa <code>HAVING</code> después de GROUP BY.', '¿Qué <b>días</b> tuvieron <b>más de 6 cacerías</b>? Muestra el día y su número.', 'GROUP BY day HAVING COUNT(*) > 6'],
   ['HAVING', '<code>WHERE</code> filtert einzelne Zeilen <b>vor</b> dem Gruppieren. Um ganze <b>Gruppen</b> zu filtern (zum Beispiel nach ihrem COUNT), nimm <code>HAVING</code> nach GROUP BY.', 'An welchen <b>Tagen</b> gab es <b>mehr als 6 Jagden</b>? Zeig den Tag und die Anzahl.', 'GROUP BY day HAVING COUNT(*) > 6'],
   unlock={'items': [11]}),
 q('4.5', 'SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT …',
   ['The full order', 'The parts always come in this order: <code>SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT</code>. WHERE picks rows, GROUP BY groups them, HAVING picks groups.', 'In the <b>nether</b> only: show each <b>player_id</b> and their total <b>XP</b> — but only players with <b>more than 30</b> XP there.', "WHERE biome = 'nether' comes before GROUP BY; HAVING SUM(xp) > 30 comes after it."],
   ['El orden completo', 'Las partes van siempre en este orden: <code>SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT</code>. WHERE elige filas, GROUP BY las agrupa, HAVING elige grupos.', 'Solo en el <b>nether</b>: muestra cada <b>player_id</b> y su <b>XP</b> total — pero solo los jugadores con <b>más de 30</b> XP allí.', "WHERE biome = 'nether' va antes de GROUP BY; HAVING SUM(xp) > 30 va después."],
   ['Die ganze Reihenfolge', 'Die Teile kommen immer in dieser Reihenfolge: <code>SELECT … FROM … WHERE … GROUP BY … HAVING … ORDER BY … LIMIT</code>. WHERE wählt Zeilen, GROUP BY gruppiert sie, HAVING wählt Gruppen.', 'Nur im <b>nether</b>: Zeig jede <b>player_id</b> und ihre gesamte <b>XP</b> — aber nur Spieler mit <b>mehr als 30</b> XP dort.', "WHERE biome = 'nether' kommt vor GROUP BY; HAVING SUM(xp) > 30 danach."],
   unlock={'items': [12]}),
 ])

# ---------------------------------------------------------------- 5
chapter('sq5', ['mobs', 'hunts'],
 {'en': 'Label Maker', 'es': 'Fábrica de etiquetas', 'de': 'Etiketten-Werkstatt'},
 {'en': 'Numbers are great, but new players want simple words: is this mob <i>dangerous</i>? Was that a <i>big</i> hunt? Time to make <b>your own columns</b>.',
  'es': 'Los números están bien, pero los jugadores nuevos quieren palabras sencillas: ¿esta criatura es <i>peligrosa</i>? ¿Fue una cacería <i>grande</i>? Es hora de crear <b>tus propias columnas</b>.',
  'de': 'Zahlen sind toll, aber neue Spieler wollen einfache Wörter: Ist dieser Mob <i>gefährlich</i>? War das eine <i>große</i> Jagd? Zeit für <b>deine eigenen Spalten</b>.'},
 [
 q('5.1', "SELECT name,\n  CASE WHEN health > 50 THEN 'big' ELSE 'small' END AS size\nFROM mobs",
   ['CASE WHEN', "<code>CASE WHEN rule THEN value ELSE other END</code> is SQL's \"if\". It makes a <b>new column</b> with a value for every row. Don't forget the <code>END</code>!", "Show every mob's <b>name</b> and a label: <code>'danger'</code> if its damage is <b>more than 10</b>, otherwise <code>'safe'</code>.", "CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END"],
   ['CASE WHEN', '<code>CASE WHEN regla THEN valor ELSE otro END</code> es el "si" de SQL. Crea una <b>columna nueva</b> con un valor para cada fila. ¡No olvides el <code>END</code>!', "Muestra el <b>name</b> de cada criatura y una etiqueta: <code>'danger'</code> si su daño es <b>mayor que 10</b>, si no <code>'safe'</code>.", "CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END"],
   ['CASE WHEN', '<code>CASE WHEN regel THEN wert ELSE anderer END</code> ist das "wenn" von SQL. Es macht eine <b>neue Spalte</b> mit einem Wert für jede Zeile. Vergiss das <code>END</code> nicht!', "Zeig den <b>name</b> jedes Mobs und ein Etikett: <code>'danger'</code>, wenn sein Schaden <b>größer als 10</b> ist, sonst <code>'safe'</code>.", "CASE WHEN damage > 10 THEN 'danger' ELSE 'safe' END"],
   freeNames=True, unlock={'items': [13]}),
 q('5.2', "CASE WHEN health >= 100 THEN 'giant'\n     WHEN health >= 20 THEN 'strong'\n     ELSE 'weak' END",
   ['Several WHENs', 'You can stack WHENs. SQL checks them <b>from top to bottom</b> and uses the <b>first</b> one that is true — so put the strictest rule first.', "Show <b>name</b> and a rank: <code>'boss'</code> if damage is <b>20 or more</b>, <code>'fighter'</code> if damage is <b>5 or more</b>, otherwise <code>'harmless'</code>.", 'First WHEN damage >= 20, then WHEN damage >= 5, then ELSE.'],
   ['Varios WHEN', 'Puedes poner varios WHEN. SQL los revisa <b>de arriba abajo</b> y usa el <b>primero</b> que sea cierto — así que pon primero la regla más estricta.', "Muestra <b>name</b> y un rango: <code>'boss'</code> si el daño es <b>20 o más</b>, <code>'fighter'</code> si es <b>5 o más</b>, si no <code>'harmless'</code>.", 'Primero WHEN damage >= 20, luego WHEN damage >= 5, luego ELSE.'],
   ['Mehrere WHENs', 'Du kannst mehrere WHENs stapeln. SQL prüft sie <b>von oben nach unten</b> und nimmt das <b>erste</b>, das stimmt — also kommt die strengste Regel zuerst.', "Zeig <b>name</b> und einen Rang: <code>'boss'</code> bei Schaden <b>20 oder mehr</b>, <code>'fighter'</code> bei <b>5 oder mehr</b>, sonst <code>'harmless'</code>.", 'Zuerst WHEN damage >= 20, dann WHEN damage >= 5, dann ELSE.'],
   freeNames=True, unlock={'items': [14]}),
 q('5.3', 'SELECT LOWER(name), LENGTH(home) FROM mobs',
   ['Text functions', '<code>UPPER(text)</code> makes CAPITALS, <code>LOWER(text)</code> small letters, <code>LENGTH(text)</code> counts the letters.', "Show every mob's name in <b>CAPITALS</b> and <b>how many letters</b> its name has.", 'UPPER(name), LENGTH(name)'],
   ['Funciones de texto', '<code>UPPER(texto)</code> pone MAYÚSCULAS, <code>LOWER(texto)</code> minúsculas, <code>LENGTH(texto)</code> cuenta las letras.', 'Muestra el nombre de cada criatura en <b>MAYÚSCULAS</b> y <b>cuántas letras</b> tiene.', 'UPPER(name), LENGTH(name)'],
   ['Textfunktionen', '<code>UPPER(text)</code> macht GROSSBUCHSTABEN, <code>LOWER(text)</code> kleine, <code>LENGTH(text)</code> zählt die Buchstaben.', 'Zeig den Namen jedes Mobs in <b>GROSSBUCHSTABEN</b> und <b>wie viele Buchstaben</b> er hat.', 'UPPER(name), LENGTH(name)'],
   freeNames=True, unlock={'items': [15]}),
 q('5.4', "SELECT name || ' drops ' || loot FROM mobs",
   ['Glue text with ||', "<code>||</code> glues pieces of text together. Mix columns with your own text in quotes — and don't forget the spaces!", 'Make a sentence for every mob, like <code>Creeper lives in the overworld</code>.', "name || ' lives in the ' || home"],
   ['Pegar texto con ||', '<code>||</code> pega trozos de texto. Mezcla columnas con tu propio texto entre comillas — ¡y no olvides los espacios!', 'Haz una frase para cada criatura, como <code>Creeper lives in the overworld</code>.', "name || ' lives in the ' || home"],
   ['Text kleben mit ||', '<code>||</code> klebt Textstücke zusammen. Misch Spalten mit eigenem Text in Anführungszeichen — und vergiss die Leerzeichen nicht!', 'Bau für jeden Mob einen Satz, zum Beispiel <code>Creeper lives in the overworld</code>.', "name || ' lives in the ' || home"],
   freeNames=True, unlock={'items': [16]}),
 q('5.5', "SELECT CASE WHEN health >= 20 THEN 'tank' ELSE 'squishy' END AS size,\n  COUNT(*)\nFROM mobs GROUP BY size",
   ['Group by your label', 'A CASE column can be grouped like any other column. Name it with <code>AS</code>, then <code>GROUP BY</code> that name.', "Label each hunt <code>'big'</code> if it gave <b>10 XP or more</b>, otherwise <code>'small'</code>. Count how many hunts are big and how many are small.", 'CASE … END AS size, COUNT(*) … GROUP BY size'],
   ['Agrupar por tu etiqueta', 'Una columna CASE se puede agrupar como cualquier otra. Ponle nombre con <code>AS</code> y luego haz <code>GROUP BY</code> con ese nombre.', "Etiqueta cada cacería como <code>'big'</code> si dio <b>10 XP o más</b>, si no <code>'small'</code>. Cuenta cuántas son big y cuántas small.", 'CASE … END AS size, COUNT(*) … GROUP BY size'],
   ['Nach deinem Etikett gruppieren', 'Eine CASE-Spalte kann man gruppieren wie jede andere. Gib ihr mit <code>AS</code> einen Namen, dann <code>GROUP BY</code> mit diesem Namen.', "Nenn jede Jagd <code>'big'</code>, wenn sie <b>10 XP oder mehr</b> gebracht hat, sonst <code>'small'</code>. Zähl, wie viele big und wie viele small sind.", 'CASE … END AS size, COUNT(*) … GROUP BY size'],
   freeNames=True),
 ])

# ---------------------------------------------------------------- 6
chapter('sq6', ['hunts', 'players', 'mobs', 'items'],
 {'en': 'Connect the Tables', 'es': 'Conecta las tablas', 'de': 'Tabellen verbinden'},
 {'en': 'The hunt log only has numbers like <code>player_id = 3</code>. Who is player 3? Which mob is <code>mob_id = 6</code>? The answers are in other tables — and <code>JOIN</code> connects them. This is the superpower of SQL.',
  'es': 'El registro de cacerías solo tiene números como <code>player_id = 3</code>. ¿Quién es el jugador 3? ¿Qué criatura es <code>mob_id = 6</code>? Las respuestas están en otras tablas — y <code>JOIN</code> las conecta. Es el superpoder de SQL.',
  'de': 'Im Jagdbuch stehen nur Zahlen wie <code>player_id = 3</code>. Wer ist Spieler 3? Welcher Mob ist <code>mob_id = 6</code>? Die Antworten stehen in anderen Tabellen — und <code>JOIN</code> verbindet sie. Das ist die Superkraft von SQL.'},
 [
 q('6.1', 'SELECT hunts.day, players.name\nFROM hunts\nJOIN players ON hunts.player_id = players.id',
   ['JOIN … ON', '<code>JOIN</code> puts two tables side by side. <code>ON</code> says which columns must match: <code>hunts.mob_id = mobs.id</code>. When both tables have a column with the same name, write <code>table.column</code>.', 'Show the <b>day</b> of every hunt and the <b>name of the mob</b> that was hunted.', 'JOIN mobs ON hunts.mob_id = mobs.id, then SELECT hunts.day, mobs.name'],
   ['JOIN … ON', '<code>JOIN</code> pone dos tablas lado a lado. <code>ON</code> dice qué columnas deben coincidir: <code>hunts.mob_id = mobs.id</code>. Si las dos tablas tienen una columna con el mismo nombre, escribe <code>tabla.columna</code>.', 'Muestra el <b>day</b> de cada cacería y el <b>nombre de la criatura</b> cazada.', 'JOIN mobs ON hunts.mob_id = mobs.id, luego SELECT hunts.day, mobs.name'],
   ['JOIN … ON', '<code>JOIN</code> stellt zwei Tabellen nebeneinander. <code>ON</code> sagt, welche Spalten zusammenpassen müssen: <code>hunts.mob_id = mobs.id</code>. Haben beide Tabellen eine Spalte mit gleichem Namen, schreib <code>tabelle.spalte</code>.', 'Zeig den <b>day</b> jeder Jagd und den <b>Namen des Mobs</b>, der gejagt wurde.', 'JOIN mobs ON hunts.mob_id = mobs.id, dann SELECT hunts.day, mobs.name'],
   ),
 q('6.2', 'SELECT h.day, m.name\nFROM hunts h\nJOIN mobs m ON h.mob_id = m.id',
   ['Short table names', 'Writing <code>hunts.</code> again and again is long. Give a table a short name right after it: <code>FROM hunts h JOIN players p</code>. Then write <code>h.xp</code>, <code>p.name</code>.', "Show each <b>player's name</b> and the <b>XP</b> of each of their hunts.", 'FROM hunts h JOIN players p ON h.player_id = p.id'],
   ['Nombres cortos de tabla', 'Escribir <code>hunts.</code> una y otra vez es largo. Dale a la tabla un nombre corto justo detrás: <code>FROM hunts h JOIN players p</code>. Luego escribe <code>h.xp</code>, <code>p.name</code>.', 'Muestra el <b>nombre de cada jugador</b> y la <b>XP</b> de cada una de sus cacerías.', 'FROM hunts h JOIN players p ON h.player_id = p.id'],
   ['Kurze Tabellennamen', 'Immer wieder <code>hunts.</code> zu schreiben ist lang. Gib einer Tabelle direkt dahinter einen kurzen Namen: <code>FROM hunts h JOIN players p</code>. Dann schreibst du <code>h.xp</code>, <code>p.name</code>.', 'Zeig den <b>Namen jedes Spielers</b> und die <b>XP</b> jeder seiner Jagden.', 'FROM hunts h JOIN players p ON h.player_id = p.id'],
   ),
 q('6.3', 'SELECT m.type, COUNT(*)\nFROM hunts h JOIN mobs m ON h.mob_id = m.id\nGROUP BY m.type',
   ['JOIN + GROUP BY', 'Everything you learned still works after a JOIN: WHERE, GROUP BY, ORDER BY…', 'Make a <b>leaderboard</b>: each <b>player name</b> with their <b>total XP</b>, best first.', 'JOIN players, GROUP BY p.name, SUM(h.xp) AS total, ORDER BY total DESC'],
   ['JOIN + GROUP BY', 'Todo lo que aprendiste sigue funcionando después de un JOIN: WHERE, GROUP BY, ORDER BY…', 'Haz una <b>clasificación</b>: el <b>nombre de cada jugador</b> con su <b>XP total</b>, el mejor primero.', 'JOIN players, GROUP BY p.name, SUM(h.xp) AS total, ORDER BY total DESC'],
   ['JOIN + GROUP BY', 'Alles, was du gelernt hast, klappt auch nach einem JOIN: WHERE, GROUP BY, ORDER BY…', 'Mach eine <b>Bestenliste</b>: jeder <b>Spielername</b> mit seiner <b>gesamten XP</b>, der Beste zuerst.', 'JOIN players, GROUP BY p.name, SUM(h.xp) AS total, ORDER BY total DESC'],
   orderCol=1),
 q('6.4', 'SELECT m.name, i.rarity\nFROM mobs m JOIN items i ON m.loot = i.name',
   ['Join on text', "The matching columns don't have to be ids. Every mob's <code>loot</code> is the <code>name</code> of an item.", "Show each mob's <b>name</b> and how many <b>emeralds</b> its loot is worth (<code>value</code>).", 'JOIN items i ON m.loot = i.name, then SELECT m.name, i.value'],
   ['Unir por texto', 'Las columnas que coinciden no tienen que ser ids. El <code>loot</code> de cada criatura es el <code>name</code> de un objeto.', 'Muestra el <b>name</b> de cada criatura y cuántas <b>esmeraldas</b> vale su botín (<code>value</code>).', 'JOIN items i ON m.loot = i.name, luego SELECT m.name, i.value'],
   ['Über Text verbinden', 'Die passenden Spalten müssen keine ids sein. Der <code>loot</code> jedes Mobs ist der <code>name</code> eines Gegenstands.', 'Zeig den <b>name</b> jedes Mobs und wie viele <b>Smaragde</b> seine Beute wert ist (<code>value</code>).', 'JOIN items i ON m.loot = i.name, dann SELECT m.name, i.value'],
   ),
 q('6.5', 'SELECT m.name, i.value\nFROM mobs m LEFT JOIN items i ON m.loot = i.name',
   ['LEFT JOIN', 'A normal JOIN <b>drops</b> rows without a match. <code>LEFT JOIN</code> keeps <b>every</b> row of the first table; where nothing matches, the other table\'s columns are <code>NULL</code>.', 'One player has <b>never been hunting</b>. Find their <b>name</b>.', 'players p LEFT JOIN hunts h ON p.id = h.player_id … WHERE h.id IS NULL'],
   ['LEFT JOIN', 'Un JOIN normal <b>quita</b> las filas sin pareja. <code>LEFT JOIN</code> mantiene <b>todas</b> las filas de la primera tabla; donde no hay coincidencia, las columnas de la otra tabla son <code>NULL</code>.', 'Un jugador <b>nunca ha ido de caza</b>. Encuentra su <b>nombre</b>.', 'players p LEFT JOIN hunts h ON p.id = h.player_id … WHERE h.id IS NULL'],
   ['LEFT JOIN', 'Ein normaler JOIN <b>wirft</b> Zeilen ohne Partner raus. <code>LEFT JOIN</code> behält <b>jede</b> Zeile der ersten Tabelle; wo nichts passt, sind die Spalten der anderen Tabelle <code>NULL</code>.', 'Ein Spieler war <b>noch nie jagen</b>. Finde seinen <b>Namen</b>.', 'players p LEFT JOIN hunts h ON p.id = h.player_id … WHERE h.id IS NULL'],
   ),
 q('6.6', 'SELECT p.name, m.name\nFROM hunts h\nJOIN players p ON h.player_id = p.id\nJOIN mobs m ON h.mob_id = m.id',
   ['Three tables', 'You can JOIN again and again: <code>FROM hunts h JOIN players p ON … JOIN mobs m ON …</code>', 'Who hunts the most <b>hostile</b> mobs? Show each <b>player name</b> and how many hostile mobs they hunted, most first.', "Join players and mobs, WHERE m.type = 'hostile', GROUP BY p.name, ORDER BY COUNT(*) DESC"],
   ['Tres tablas', 'Puedes hacer JOIN una y otra vez: <code>FROM hunts h JOIN players p ON … JOIN mobs m ON …</code>', '¿Quién caza más criaturas <b>hostile</b>? Muestra el <b>nombre de cada jugador</b> y cuántas hostiles cazó, de más a menos.', "Une players y mobs, WHERE m.type = 'hostile', GROUP BY p.name, ORDER BY COUNT(*) DESC"],
   ['Drei Tabellen', 'Du kannst immer weiter JOINen: <code>FROM hunts h JOIN players p ON … JOIN mobs m ON …</code>', 'Wer jagt die meisten <b>hostile</b> Mobs? Zeig jeden <b>Spielernamen</b> und wie viele feindliche Mobs er gejagt hat, die meisten zuerst.', "Verbinde players und mobs, WHERE m.type = 'hostile', GROUP BY p.name, ORDER BY COUNT(*) DESC"],
   orderCol=1),
 ])

# ---------------------------------------------------------------- 7
chapter('sq7', ['chest_log', 'trades', 'players', 'items'],
 {'en': 'Boss: The Diamond Thief', 'es': 'Jefe: el ladrón de diamantes', 'de': 'Boss: Der Diamantendieb'},
 {'en': 'Boss case! 🕵️ On day 8, Steve put <b>12 diamonds</b> in the village chest. On the morning of day 10 the chest was <b>empty</b>. Two new tables hold the clues: <code>chest_log</code> (who used the chest, when, and what they put in or took out) and <code>trades</code> (what players sold to the wandering trader). Solve it step by step.',
  'es': '¡Caso jefe! 🕵️ El día 8, Steve guardó <b>12 diamantes</b> en el cofre de la aldea. La mañana del día 10 el cofre estaba <b>vacío</b>. Dos tablas nuevas tienen las pistas: <code>chest_log</code> (quién usó el cofre, cuándo, y qué metió o sacó) y <code>trades</code> (qué vendieron los jugadores al comerciante). Resuélvelo paso a paso.',
  'de': 'Boss-Fall! 🕵️ An Tag 8 hat Steve <b>12 Diamanten</b> in die Dorftruhe gelegt. Am Morgen von Tag 10 war die Truhe <b>leer</b>. Zwei neue Tabellen enthalten die Hinweise: <code>chest_log</code> (wer die Truhe wann benutzt hat und was er hineingelegt oder herausgenommen hat) und <code>trades</code> (was Spieler dem Händler verkauft haben). Lös den Fall Schritt für Schritt.'},
 [
 q('7.1', 'SELECT * FROM hunts ORDER BY day, xp DESC',
   ['Clue 1: the chest', 'Detectives start with the facts. You can sort by two columns: <code>ORDER BY day, hour</code> sorts by day first, then by hour.', 'Show every row of <code>chest_log</code> about <b>diamonds</b>, in time order (<b>day</b>, then <b>hour</b>). How many diamonds are missing?', "WHERE item = 'diamond' ORDER BY day, hour"],
   ['Pista 1: el cofre', 'Los detectives empiezan por los hechos. Puedes ordenar por dos columnas: <code>ORDER BY day, hour</code> ordena primero por día y luego por hora.', 'Muestra cada fila de <code>chest_log</code> sobre <b>diamantes</b>, en orden de tiempo (<b>day</b> y luego <b>hour</b>). ¿Cuántos diamantes faltan?', "WHERE item = 'diamond' ORDER BY day, hour"],
   ['Hinweis 1: die Truhe', 'Detektive fangen mit den Fakten an. Du kannst nach zwei Spalten sortieren: <code>ORDER BY day, hour</code> sortiert zuerst nach Tag, dann nach Stunde.', 'Zeig jede Zeile aus <code>chest_log</code> über <b>Diamanten</b>, zeitlich sortiert (<b>day</b>, dann <b>hour</b>). Wie viele Diamanten fehlen?', "WHERE item = 'diamond' ORDER BY day, hour"],
   orderCol=1),
 q('7.2', None,
   ['Clue 2: night visitors', 'The chest was fine on the evening of day 9. Who came at night? Use a JOIN to turn player_ids into names.', 'Show the <b>name</b> and <b>hour</b> of everyone who used the chest on <b>day 9</b> at <b>20:00 or later</b>. These are your suspects.', 'chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20'],
   ['Pista 2: visitas nocturnas', 'La tarde del día 9 el cofre estaba bien. ¿Quién vino de noche? Usa un JOIN para cambiar los player_id por nombres.', 'Muestra el <b>nombre</b> y la <b>hour</b> de todos los que usaron el cofre el <b>día 9</b> a las <b>20:00 o más tarde</b>. Son tus sospechosos.', 'chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20'],
   ['Hinweis 2: nächtliche Besucher', 'Am Abend von Tag 9 war die Truhe noch in Ordnung. Wer kam in der Nacht? Mit einem JOIN machst du aus player_ids Namen.', 'Zeig <b>Name</b> und <b>hour</b> aller, die die Truhe an <b>Tag 9</b> um <b>20 Uhr oder später</b> benutzt haben. Das sind deine Verdächtigen.', 'chest_log c JOIN players p ON c.player_id = p.id WHERE c.day = 9 AND c.hour >= 20'],
   ),
 q('7.3', 'SELECT m.name, m.health * i.value\nFROM mobs m JOIN items i ON m.loot = i.name',
   ['Clue 3: follow the money', 'A thief wants to sell the loot. You can calculate across joined tables: <code>t.amount * i.value</code>.', 'Show every <b>diamond trade</b>: the player\'s <b>name</b>, the <b>day</b>, and how many <b>emeralds</b> it was worth (amount × value).', 'Join trades t with players p and with items i ON t.item = i.name; SELECT p.name, t.day, t.amount * i.value'],
   ['Pista 3: sigue el dinero', 'Un ladrón quiere vender el botín. Puedes calcular entre tablas unidas: <code>t.amount * i.value</code>.', 'Muestra cada <b>venta de diamantes</b>: el <b>nombre</b> del jugador, el <b>day</b> y cuántas <b>esmeraldas</b> valió (amount × value).', 'Une trades t con players p y con items i ON t.item = i.name; SELECT p.name, t.day, t.amount * i.value'],
   ['Hinweis 3: folge dem Geld', 'Ein Dieb will die Beute verkaufen. Du kannst über verbundene Tabellen rechnen: <code>t.amount * i.value</code>.', 'Zeig jeden <b>Diamantenverkauf</b>: den <b>Namen</b> des Spielers, den <b>day</b> und wie viele <b>Smaragde</b> er wert war (amount × value).', 'Verbinde trades t mit players p und mit items i ON t.item = i.name; SELECT p.name, t.day, t.amount * i.value'],
   freeNames=True),
 q('7.4', None,
   ['Clue 4: who sold how much?', 'Luna took 2 diamonds and wrote it in the log — that\'s allowed. But 10 diamonds are still missing…', 'After day 9 (<b>day &gt; 9</b>), how many diamonds did each player sell <b>in total</b>? Show the <b>name</b> and the total.', "WHERE t.item = 'diamond' AND t.day > 9, GROUP BY p.name, SUM(t.amount)"],
   ['Pista 4: ¿quién vendió cuánto?', 'Luna sacó 2 diamantes y lo apuntó en el registro — eso está permitido. Pero aún faltan 10…', 'Después del día 9 (<b>day &gt; 9</b>), ¿cuántos diamantes vendió cada jugador <b>en total</b>? Muestra el <b>nombre</b> y el total.', "WHERE t.item = 'diamond' AND t.day > 9, GROUP BY p.name, SUM(t.amount)"],
   ['Hinweis 4: Wer hat wie viel verkauft?', 'Luna hat 2 Diamanten genommen und es ins Log geschrieben — das ist erlaubt. Aber 10 fehlen immer noch…', 'Wie viele Diamanten hat jeder Spieler nach Tag 9 (<b>day &gt; 9</b>) <b>insgesamt</b> verkauft? Zeig den <b>Namen</b> und die Summe.', "WHERE t.item = 'diamond' AND t.day > 9, GROUP BY p.name, SUM(t.amount)"],
   ),
 q('7.5', "SELECT name FROM players\nWHERE id IN (SELECT player_id FROM hunts WHERE biome = 'caves')",
   ['Subquery with IN', 'A query can live <b>inside</b> another one. <code>WHERE id IN (SELECT player_id FROM …)</code> first runs the inner query, then keeps only the ids that are in its result.', 'Name the thief: the player who used the chest on <b>night 9</b> (hour ≥ 20) <b>and</b> sold diamonds <b>after day 9</b>. Use two <code>IN (SELECT …)</code>.', 'SELECT name FROM players WHERE id IN (… night visitors …) AND id IN (… diamond sellers after day 9 …)'],
   ['Subconsulta con IN', 'Una consulta puede vivir <b>dentro</b> de otra. <code>WHERE id IN (SELECT player_id FROM …)</code> primero ejecuta la consulta de dentro y luego se queda solo con los ids de su resultado.', 'Nombra al ladrón: el jugador que usó el cofre la <b>noche del 9</b> (hour ≥ 20) <b>y</b> vendió diamantes <b>después del día 9</b>. Usa dos <code>IN (SELECT …)</code>.', 'SELECT name FROM players WHERE id IN (… visitas nocturnas …) AND id IN (… vendedores de diamantes después del día 9 …)'],
   ['Unterabfrage mit IN', 'Eine Abfrage kann <b>in</b> einer anderen stecken. <code>WHERE id IN (SELECT player_id FROM …)</code> führt zuerst die innere Abfrage aus und behält dann nur die ids aus ihrem Ergebnis.', 'Nenn den Dieb: den Spieler, der in <b>Nacht 9</b> (hour ≥ 20) an der Truhe war <b>und</b> <b>nach Tag 9</b> Diamanten verkauft hat. Nimm zwei <code>IN (SELECT …)</code>.', 'SELECT name FROM players WHERE id IN (… nächtliche Besucher …) AND id IN (… Diamantenverkäufer nach Tag 9 …)'],
   ),
 q('7.6', 'WITH big AS (SELECT * FROM mobs WHERE health > 20)\nSELECT name FROM big',
   ['WITH', '<code>WITH name AS (SELECT …)</code> gives a query a name, so you can use it like a table further down. It makes long detective work readable.', "Write the <b>case report</b>: using <code>WITH</code>, make a list of night visitors and a list of diamonds sold after day 9, then show the thief's <b>name</b> and <b>how many diamonds</b> they sold.", 'WITH suspects AS (…), sold AS (SELECT player_id, SUM(amount) AS diamonds … GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN …'],
   ['WITH', '<code>WITH nombre AS (SELECT …)</code> le pone nombre a una consulta, para usarla más abajo como si fuera una tabla. Hace legible el trabajo de detective largo.', 'Escribe el <b>informe del caso</b>: con <code>WITH</code>, haz una lista de visitas nocturnas y otra de diamantes vendidos después del día 9, y muestra el <b>nombre</b> del ladrón y <b>cuántos diamantes</b> vendió.', 'WITH suspects AS (…), sold AS (SELECT player_id, SUM(amount) AS diamonds … GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN …'],
   ['WITH', '<code>WITH name AS (SELECT …)</code> gibt einer Abfrage einen Namen, damit du sie weiter unten wie eine Tabelle benutzen kannst. So bleibt lange Detektivarbeit lesbar.', 'Schreib den <b>Fallbericht</b>: Mach mit <code>WITH</code> eine Liste der nächtlichen Besucher und eine der nach Tag 9 verkauften Diamanten, und zeig dann den <b>Namen</b> des Diebs und <b>wie viele Diamanten</b> er verkauft hat.', 'WITH suspects AS (…), sold AS (SELECT player_id, SUM(amount) AS diamonds … GROUP BY player_id) SELECT p.name, s.diamonds FROM players p JOIN …'],
   freeNames=True),
 ], boss=True)

# ---------------------------------------------------------------- 8
chapter('sq8', ['mobs', 'hunts', 'players'],
 {'en': 'Bonus: Leaderboards', 'es': 'Extra: clasificaciones', 'de': 'Bonus: Bestenlisten'},
 {'en': 'Bonus chapter ⭐ — tools that real analysts love. <b>Window functions</b> calculate across rows <i>without</i> squashing them into groups: ranks, running totals, the best in each group.',
  'es': 'Capítulo extra ⭐ — herramientas que encantan a los analistas. Las <b>funciones de ventana</b> calculan entre filas <i>sin</i> juntarlas en grupos: puestos, totales acumulados, el mejor de cada grupo.',
  'de': 'Bonuskapitel ⭐ — Werkzeuge, die echte Analysten lieben. <b>Fensterfunktionen</b> rechnen über Zeilen hinweg, <i>ohne</i> sie zu Gruppen zusammenzuquetschen: Ränge, laufende Summen, die Besten jeder Gruppe.'},
 [
 q('8.1', 'SELECT name, damage,\n  RANK() OVER (ORDER BY damage DESC) AS place\nFROM mobs',
   ['RANK() OVER', '<code>RANK() OVER (ORDER BY … DESC)</code> gives every row its place: 1, 2, 3… Rows that tie get the same place.', 'Rank all mobs by <b>health</b>, highest first. Show <b>name</b>, <b>health</b> and the <b>rank</b>.', 'RANK() OVER (ORDER BY health DESC)'],
   ['RANK() OVER', '<code>RANK() OVER (ORDER BY … DESC)</code> le da a cada fila su puesto: 1, 2, 3… Las filas empatadas reciben el mismo puesto.', 'Clasifica todas las criaturas por <b>health</b>, de mayor a menor. Muestra <b>name</b>, <b>health</b> y el <b>puesto</b>.', 'RANK() OVER (ORDER BY health DESC)'],
   ['RANK() OVER', '<code>RANK() OVER (ORDER BY … DESC)</code> gibt jeder Zeile ihren Platz: 1, 2, 3… Gleichstände bekommen denselben Platz.', 'Ordne alle Mobs nach <b>health</b>, das höchste zuerst. Zeig <b>name</b>, <b>health</b> und den <b>Rang</b>.', 'RANK() OVER (ORDER BY health DESC)'],
   freeNames=True),
 q('8.2', 'SELECT name, home, health,\n  RANK() OVER (PARTITION BY home ORDER BY health DESC)\nFROM mobs',
   ['PARTITION BY', '<code>PARTITION BY type</code> restarts the ranking for every type — a "rank inside each group".', 'Rank the mobs by <b>damage</b> <b>inside each type</b>. Show <b>name</b>, <b>type</b>, <b>damage</b> and the rank.', 'RANK() OVER (PARTITION BY type ORDER BY damage DESC)'],
   ['PARTITION BY', '<code>PARTITION BY type</code> reinicia la clasificación para cada tipo — un "puesto dentro de cada grupo".', 'Clasifica las criaturas por <b>damage</b> <b>dentro de cada type</b>. Muestra <b>name</b>, <b>type</b>, <b>damage</b> y el puesto.', 'RANK() OVER (PARTITION BY type ORDER BY damage DESC)'],
   ['PARTITION BY', '<code>PARTITION BY type</code> fängt die Rangliste für jeden Typ neu an — ein "Rang innerhalb jeder Gruppe".', 'Ordne die Mobs nach <b>damage</b> <b>innerhalb jedes type</b>. Zeig <b>name</b>, <b>type</b>, <b>damage</b> und den Rang.', 'RANK() OVER (PARTITION BY type ORDER BY damage DESC)'],
   freeNames=True),
 q('8.3', 'WITH d AS (SELECT day, COUNT(*) AS n FROM hunts GROUP BY day)\nSELECT day, n, SUM(n) OVER (ORDER BY day) FROM d',
   ['Running total', '<code>SUM(x) OVER (ORDER BY day)</code> adds up everything <b>so far</b> — a running total. Tip: first make daily totals with <code>WITH</code>, then run the window over them.', 'Show each <b>day</b>, the <b>XP earned that day</b>, and the <b>running total</b> of XP up to that day.', 'WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d'],
   ['Total acumulado', '<code>SUM(x) OVER (ORDER BY day)</code> suma todo lo que va <b>hasta ahora</b> — un total acumulado. Consejo: primero calcula los totales por día con <code>WITH</code> y luego aplica la ventana.', 'Muestra cada <b>day</b>, la <b>XP ganada ese día</b> y el <b>total acumulado</b> de XP hasta ese día.', 'WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d'],
   ['Laufende Summe', '<code>SUM(x) OVER (ORDER BY day)</code> zählt alles <b>bis jetzt</b> zusammen — eine laufende Summe. Tipp: Rechne zuerst mit <code>WITH</code> die Tagessummen aus und lass dann das Fenster darüber laufen.', 'Zeig jeden <b>day</b>, die <b>XP dieses Tages</b> und die <b>laufende Summe</b> der XP bis zu diesem Tag.', 'WITH d AS (SELECT day, SUM(xp) AS xp FROM hunts GROUP BY day) SELECT day, xp, SUM(xp) OVER (ORDER BY day) FROM d'],
   freeNames=True),
 q('8.4', None,
   ['Final leaderboard', 'Put it all together: JOIN, GROUP BY, WITH and RANK — this is exactly how real game leaderboards are built.', 'Build the final leaderboard: each <b>player name</b>, their <b>total XP</b>, and their <b>rank</b>.', 'WITH t AS (… player name + SUM(xp) …) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t'],
   ['Clasificación final', 'Júntalo todo: JOIN, GROUP BY, WITH y RANK — así se construyen las clasificaciones de los juegos de verdad.', 'Construye la clasificación final: el <b>nombre de cada jugador</b>, su <b>XP total</b> y su <b>puesto</b>.', 'WITH t AS (… nombre + SUM(xp) …) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t'],
   ['Die finale Bestenliste', 'Alles zusammen: JOIN, GROUP BY, WITH und RANK — genau so werden echte Spiel-Bestenlisten gebaut.', 'Bau die finale Bestenliste: jeder <b>Spielername</b>, seine <b>gesamte XP</b> und sein <b>Rang</b>.', 'WITH t AS (… Spielername + SUM(xp) …) SELECT name, total, RANK() OVER (ORDER BY total DESC) FROM t'],
   freeNames=True),
 ], bonus=True)

out = sys.argv[1]
with open(out, 'w') as f:
    f.write('// Generated by gen_levels.py — SQL chapters. One new idea per quest.\n(function () {\n')
    f.write('  window.SQL_LEVELS = ' + json.dumps(CH, ensure_ascii=False, indent=1) + ';\n})();\n')
n = sum(len(c['quests']) for c in CH)
print('wrote', out, len(CH), 'chapters,', n, 'quests')
for c in CH:
    for i, qq in enumerate(c['quests']):
        for l in ('en', 'es', 'de'):
            assert all(qq['text'][l].get(k) for k in ('idea', 'lesson', 'task', 'hint')), (c['id'], i, l)
print('all quests have idea/lesson/task/hint in 3 languages')
